select 

orders.PART_ID,
shipments.PART_ID,
part.DESCRIPTION,
orders.ORDER_QTY,
shipments.SHIPPED_QTY 

from (


SELECT 
CUST_ORDER_LINE.PART_ID, 
sum(CUST_ORDER_LINE.ORDER_QTY) as ORDER_QTY

FROM VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE, VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER

WHERE CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID AND ((CUSTOMER_ORDER.ORDER_DATE Between '01/01/2022' And '12/31/2022') AND (CUST_ORDER_LINE.PART_ID Is Not Null))

group by

CUST_ORDER_LINE.PART_ID) as Orders

full outer join (


SELECT 
CUST_ORDER_LINE.PART_ID, 
sum(SHIPPER_LINE.SHIPPED_QTY) as SHIPPED_QTY
FROM VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE, VECA.dbo.SHIPPER SHIPPER, VECA.dbo.SHIPPER_LINE SHIPPER_LINE
WHERE SHIPPER.PACKLIST_ID = SHIPPER_LINE.PACKLIST_ID AND CUST_ORDER_LINE.CUST_ORDER_ID = SHIPPER_LINE.CUST_ORDER_ID AND SHIPPER_LINE.CUST_ORDER_LINE_NO = CUST_ORDER_LINE.LINE_NO AND ((CUST_ORDER_LINE.PART_ID Is Not Null) AND (SHIPPER.SHIPPED_DATE Between {ts '2022-01-01 00:00:00'} And {ts '2022-12-31 00:00:00'}))

group by 
CUST_ORDER_LINE.PART_ID ) as Shipments 

on orders.part_ID = shipments.Part_ID

left join veca.dbo.part part on part.id = isnull(orders.part_ID,shipments.part_ID)