select
TB_Det.Doc_ID,
TB_Det.Acct_ID,
round(TB_Det.Net_Amount,2) as net_amount,
TB_Det.POSTING_DATE as posting_date,
TB_Det.RECORD_CREATED AS RECORD_CREATED,
TB_Det.REFERENCE,
Z_GL_MAPPING.ACCOUNT_ID, 
Z_GL_MAPPING.DESCRIPTION, 
Z_GL_MAPPING.ACCOUNT_CLASS, 
Z_GL_MAPPING.ACCOUNT_CAT_ID, 
Z_GL_MAPPING.ACTIVE_FLAG, 
Z_GL_MAPPING.POSTING_LEVEL, 
Z_GL_MAPPING.FS, 
Z_GL_MAPPING.FS_CAT, 
Z_GL_MAPPING.FS_COND, 
Z_GL_MAPPING.FS_DET, 
Z_GL_MAPPING.CATEGORY, 
Z_GL_MAPPING.CC_CAT, 
Z_GL_MAPPING.BREAK_CAT

from (

-- Add Payables Doc Type
select
PAYABLES_PAYABLE_DIST.INVOICE_ID as Doc_ID,
PAYABLES_PAYABLE_DIST.ACCOUNT_ID as Acct_ID,
PAYABLES_PAYABLE_DIST.DEBIT_AMOUNT - PAYABLES_PAYABLE_DIST.CREDIT_AMOUNT as Net_Amount,
PAYABLES_PAYABLE_DIST.POSTING_DATE as Posting_Date,
PAYABLES_PAYABLE_DIST.REFERENCE as Reference,
PAYABLES_PAYABLE_DIST.RECORD_CREATED AS RECORD_CREATED

FROM VFIN.dbo.PAYABLES_PAYABLE_DIST PAYABLES_PAYABLE_DIST

union all 

--Add Receivable Doc Types

SELECT
RECEIVABLES_RECEIVABLE_DIST.INVOICE_ID,
RECEIVABLES_RECEIVABLE_DIST.ACCOUNT_ID,
RECEIVABLES_RECEIVABLE_DIST.DEBIT_AMOUNt - RECEIVABLES_RECEIVABLE_DIST.CREDIT_AMOUNT as Net_Amount,
RECEIVABLES_RECEIVABLE_DIST.POSTING_DATE,
RECEIVABLES_RECEIVABLE_DIST.REFERENCE,
RECEIVABLES_RECEIVABLE_DIST.RECORD_CREATED

From VFIN.dbo.RECEIVABLES_RECEIVABLE_DIST RECEIVABLES_RECEIVABLE_DIST



Union ALL

--Add Bank Adjust Doc Type
select
CASHMGMT_BANK_ADJ_DIST.ADJUSTMENT_ID,
CASHMGMT_BANK_ADJ_DIST.ACCOUNT_ID,
CASHMGMT_BANK_ADJ_DIST.DEBIT_AMOUNT - CASHMGMT_BANK_ADJ_DIST.CREDIT_AMOUNT as Net_Amount,
CASHMGMT_BANK_ADJ_DIST.POSTING_DATE,
CASHMGMT_BANK_ADJ_DIST.REFERENCE,
CASHMGMT_BANK_ADJ_DIST.RECORD_CREATED 
 
From VFIN.dbo.CASHMGMT_BANK_ADJ_DIST CASHMGMT_BANK_ADJ_DIST

Union ALL

--Add Payment Doc Type
select
CASHMGMT_PAYMENT_DIST.PAYB_INVOICE_ID,
CASHMGMT_PAYMENT_DIST.ACCOUNT_ID,
CASHMGMT_PAYMENT_DIST.DEBIT_AMOUNT - CASHMGMT_PAYMENT_DIST.CREDIT_AMOUNT as net_amount,
CASHMGMT_PAYMENT_DIST.POSTING_DATE,
CASHMGMT_PAYMENT_DIST.REFERENCE,
CASHMGMT_PAYMENT_DIST.RECORD_CREATED
 
From VFIN.dbo.CASHMGMT_PAYMENT_DIST CASHMGMT_PAYMENT_DIST

union all

--Add journal Entry Doc Type
select
LEDGER_GEN_JOURN_DIST.GEN_JOURNAL_ID,
LEDGER_GEN_JOURN_DIST.ACCOUNT_ID,
LEDGER_GEN_JOURN_DIST.DEBIT_AMOUNT - LEDGER_GEN_JOURN_DIST.CREDIT_AMOUNT as net_amount,
LEDGER_GEN_JOURN_DIST.POSTING_DATE,
LEDGER_GEN_JOURN_DIST.REFERENCE,
LEDGER_GEN_JOURN_DIST.RECORD_CREATED

From VFIN.dbo.LEDGER_GEN_JOURN_DIST LEDGER_GEN_JOURN_DIST

Union ALL
--add direct journals
select
LEDGER_DIRECT_JOURN_DIST.DIRECT_JOURNAL_ID,
LEDGER_DIRECT_JOURN_DIST.ACCOUNT_ID,
LEDGER_DIRECT_JOURN_DIST.DEBIT_AMOUNT - LEDGER_DIRECT_JOURN_DIST.CREDIT_AMOUNT as net_amount,
LEDGER_DIRECT_JOURN_DIST.POSTING_DATE,
LEDGER_DIRECT_JOURN_DIST.REFERENCE,
LEDGER_DIRECT_JOURN_DIST.RECORD_CREATED

From VFIN.dbo.LEDGER_DIRECT_JOURN_DIST LEDGER_DIRECT_JOURN_DIST) as TB_Det

left join VECA.dbo.Z_GL_MAPPING Z_GL_MAPPING on TB_Det.Acct_ID = Z_GL_MAPPING.ACCOUNT_ID

--limit to income statement and 2018 and more recent
where Z_GL_MAPPING.FS = 'IS' 