SELECT 
 concat(CUSTOMER_ORDER.ID,'/', CUST_ORDER_LINE.LINE_NO,'/', CUST_LINE_DEL.DEL_SCHED_LINE_NO) as Identifier, 
 
 CASE
	when CUST_LINE_DEL.DESIRED_SHIP_DATE is not null then  CUST_LINE_DEL.DESIRED_SHIP_DATE
	when CUST_ORDER_LINE.DESIRED_SHIP_DATE is not null then CUST_ORDER_LINE.DESIRED_SHIP_DATE
	else  CUSTOMER_ORDER.DESIRED_SHIP_DATE end as Transaction_date,

'Customer Orders' as Kind,
 CUST_ORDER_LINE.PART_ID, 
 
 case 
	when CUST_LINE_DEL.ORDER_QTY is not null then   CUST_LINE_DEL.ORDER_QTY - CUST_LINE_DEL.SHIPPED_QTY
	else CUST_ORDER_LINE.ORDER_QTY - CUST_ORDER_LINE.TOTAL_SHIPPED_QTY end as Qty

 
FROM 
VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER left join VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE 
	on CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID

left join VECA.dbo.CUST_LINE_DEL CUST_LINE_DEL 
	on CUST_ORDER_LINE.CUST_ORDER_ID = CUST_LINE_DEL.CUST_ORDER_ID AND CUST_ORDER_LINE.LINE_NO = CUST_LINE_DEL.DEL_SCHED_LINE_NO

WHERE  CUST_ORDER_LINE.PART_ID is not null