SELECT 
CUST_ORDER_LINE.PART_ID,
count(CUST_ORDER_LINE.PART_ID) as Count, 
part.description, 
PART.PRODUCT_CODE

FROM VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE, VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER, VECA.dbo.PART PART
WHERE CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID AND CUST_ORDER_LINE.PART_ID = PART.ID AND ((CUSTOMER_ORDER.CUSTOMER_PO_REF Like '%POINT REDEMPTION%') AND (CUST_ORDER_LINE.PART_ID Is Not Null) AND (CUSTOMER_ORDER.CREATE_DATE>={ts '2022-01-01 00:00:00'}))

group by 
CUST_ORDER_LINE.PART_ID,
part.description, 
PART.PRODUCT_CODE