use veca
SELECT
TRACE_ID, PRODUCT_CODE
FROM
SHIPPER
INNER JOIN SHIPPER_LINE
ON SHIPPER.PACKLIST_ID = SHIPPER_LINE.PACKLIST_ID
INNER JOIN TRACE_INV_TRANS
ON SHIPPER_LINE.TRANSACTION_ID=TRACE_INV_TRANS.TRANSACTION_ID
INNER JOIN PART
on TRACE_INV_TRANS.PART_ID = PART.ID
group by TRACE_ID, PRODUCT_CODE