SELECT 
--Select balances from the account balance table
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT_BALANCE.POSTING_DATE, 
round(LEDGER_ACCOUNT_BALANCE.DEBIT_AMOUNT - LEDGER_ACCOUNT_BALANCE.CREDIT_AMOUNT,2) as Net_Amount,

--Add GL Mapping Accounts
Z_GL_MAPPING.ACCOUNT_ID, 
Z_GL_MAPPING.DESCRIPTION, 
Z_GL_MAPPING.ACCOUNT_CLASS, 
Z_GL_MAPPING.ACCOUNT_CAT_ID, 
Z_GL_MAPPING.ACTIVE_FLAG, 
Z_GL_MAPPING.POSTING_LEVEL, 
Z_GL_MAPPING.FS, 
Z_GL_MAPPING.FS_CAT, 
Z_GL_MAPPING.FS_COND, 
Z_GL_MAPPING.FS_DET, 
Z_GL_MAPPING.CATEGORY, 
Z_GL_MAPPING.CC_CAT, 
Z_GL_MAPPING.BREAK_CAT

FROM VFIN.dbo.LEDGER_ACCOUNT_BALANCE LEDGER_ACCOUNT_BALANCE 
left join VECA.dbo.Z_GL_MAPPING Z_GL_MAPPING on LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID = Z_GL_MAPPING.ACCOUNT_ID
inner join VFIN.dbo.LEDGER_ACCOUNT LEDGER_ACCOUNT on LEDGER_ACCOUNT.Account_id = LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID

where LEDGER_ACCOUNT.POSTING_LEVEL=1

union all

select
'2195','2010-01-01',8.00,'2195','Suspense','LIAB','CL',1,1,'BS','Accrued Expenses','Current Payables','','','',''