DECLARE @SKU nvarchar(50) = '810-00058-00'
SELECT PART.DESCRIPTION, PART_LOCaTION.QTY, PART_LOCATIOn.WAREHOUSE_ID, PART_LOCATION.LOCATION_ID FROM PART_LOCATION 
join PART on PART_LOCATION.PART_ID = PART.ID where PART_ID like @SKU
and QTY > 0


DECLARE @SKU nvarchar(50) = '730-CAH%'
SELECT PART.ID, PART.DESCRIPTION, SUM(PART_LOCaTION.QTY) as TOTAL_COUNT FROM PART_LOCATION 
join PART on PART_LOCATION.PART_ID = PART.ID where PART_ID like @SKU
and WAREHOUSE_ID = 'DISTRIBUTION'
GROUP BY PART.ID, PART.DESCRIPTION