use veca
SELECT dbo.PART.COMMODITY_CODE, dbo.PART.PRODUCT_CODE, PART.ID ,TRACE_INV_TRANS.TRACE_ID, PART_LOCATION.LOCATION_ID, SUM(TRACE_INV_TRANS.QTY) AS TOTAL
  FROM [VECA].[dbo].PART
  INNER JOIN TRACE_INV_TRANS
  ON PART.ID = TRACE_INV_TRANS.PART_ID
    INNER JOIN PART_LOCATION
  ON PART.ID = PART_LOCATION.PART_ID
  WHERE PART.ID = '230-00099-02' AND PART_LOCATION.LOCATION_ID = 'DASAN' 
  GROUP BY dbo.PART.COMMODITY_CODE, dbo.PART.PRODUCT_CODE, PART.ID, TRACE_INV_TRANS.TRACE_ID, PART_LOCATION.LOCATION_ID
  HAVING (SUM(TRACE_INV_TRANS.QTY) <> 0)
 
  ORDER BY TRACE_id

  SELECT        dbo.PART.COMMODITY_CODE, dbo.PART.PRODUCT_CODE, dbo.PART.DESCRIPTION, dbo.TRACE_INV_TRANS.PART_ID, dbo.TRACE_INV_TRANS.TRACE_ID, SUM(dbo.TRACE_INV_TRANS.QTY) AS BALANCE, 
                         dbo.PART.FABRICATED, dbo.PART.PURCHASED, dbo.PART.STOCK_UM
FROM            dbo.TRACE_INV_TRANS INNER JOIN
                         dbo.PART ON dbo.PART.ID = dbo.TRACE_INV_TRANS.PART_ID

						 WHERE PART.ID ='230-00099-02'
GROUP BY dbo.PART.COMMODITY_CODE, dbo.PART.PRODUCT_CODE, dbo.PART.DESCRIPTION, dbo.TRACE_INV_TRANS.PART_ID, dbo.TRACE_INV_TRANS.TRACE_ID, dbo.PART.FABRICATED, dbo.PART.PURCHASED, 
                         dbo.PART.STOCK_UM
HAVING        (SUM(dbo.TRACE_INV_TRANS.QTY) <> 0)
  

    SELECT        SUM(dbo.TRACE_INV_TRANS.QTY) AS BALANCE
                        
FROM            dbo.TRACE_INV_TRANS 
						 WHERE TRACE_INV_TRANS.PART_ID ='230-00099-02'
GROUP BY dbo.PART.COMMODITY_CODE, dbo.PART.PRODUCT_CODE, dbo.PART.DESCRIPTION, dbo.TRACE_INV_TRANS.PART_ID, dbo.TRACE_INV_TRANS.TRACE_ID, dbo.PART.FABRICATED, dbo.PART.PURCHASED, 
                         dbo.PART.STOCK_UM
HAVING        (SUM(dbo.TRACE_INV_TRANS.QTY) <> 0)