select 
PART_LOCATION.PART_ID,
PART_LOCATION.QTY,
cost.Average_Cost,
part_location.qty * cost.Average_Cost as location_value,
PART_LOCATION.LOCATION_ID,
PART_LOCATION.WAREHOUSE_ID,
part.Description,
part.commodity_code,
part.Product_code,

case	part_location.location_ID	
when	'AUTEC-STATESVIL'	then	'29 Axis'
when	'CONSIGN'	then	'Consign'
when	'DASAN'	then	'Consign-Obsolete'
when	'LASTMILE'	then	'LastMile'
when	'LOTH_WALT1'	then	'Lother Walther'
when	'STORES'	then	'Consign-Obsolete'
when	'DASAN-USA'	then	'Dasan'
when	'XFER'	then	'Xfer'
when	'EPHRAIM'	then	'Ephraim'
when	'R1'	then	'Fullfillment'
when	'ACT-FREEZER'	then	'Obsolete Locations'
when	'ARCA1'	then	'Receiving Cage - Serialized'
when	'ARCA2'	then	'Receiving Cage - Serialized'
when	'ARCA3'	then	'Receiving Cage - Serialized'
when	'ARCA4'	then	'Receiving Cage - Serialized'
when	'ASSEMBLY'	then	'WIP - Obsolete Location'
when	'BARRELCELL'	then	'WIP'
when	'BLACKWING'	then	'C1 - Obsolete Location'
when	'BUILDING 2'	then	'C1 - Obsolete Location'
when	'C1'	then	'C1 - Obsolete Location'
when	'C1A10R1S1'	then	'C1 - Obsolete Location'
when	'C1A10R1S2'	then	'C1 - Obsolete Location'
when	'C1A10R1S3'	then	'C1 - Obsolete Location'
when	'C1A10R1S4'	then	'C1 - Obsolete Location'
when	'C1A10R1S5'	then	'C1 - Obsolete Location'
when	'C1A10R1S6'	then	'C1 - Obsolete Location'
when	'C1A10R1S7'	then	'C1 - Obsolete Location'
when	'C1A10R1S8'	then	'C1 - Obsolete Location'
when	'C1A10R2S2'	then	'C1 - Obsolete Location'
when	'C1A10R2S3'	then	'C1 - Obsolete Location'
when	'C1A10R2S4'	then	'C1 - Obsolete Location'
when	'C1A10R2S5'	then	'C1 - Obsolete Location'
when	'C1A10R2S6'	then	'C1 - Obsolete Location'
when	'C1A10R2S7'	then	'C1 - Obsolete Location'
when	'C1A10R2S8'	then	'C1 - Obsolete Location'
when	'C1A10R3S2'	then	'C1 - Obsolete Location'
when	'C1A10R3S3'	then	'C1 - Obsolete Location'
when	'C1A10R3S4'	then	'C1 - Obsolete Location'
when	'C1A10R3S5'	then	'C1 - Obsolete Location'
when	'C1A10R3S6'	then	'C1 - Obsolete Location'
when	'C1A10R3S7'	then	'C1 - Obsolete Location'
when	'C1A10R3S8'	then	'C1 - Obsolete Location'
when	'C1A10R4S1'	then	'C1 - Obsolete Location'
when	'C1A10R4S2'	then	'C1 - Obsolete Location'
when	'C1A10R4S3'	then	'C1 - Obsolete Location'
when	'C1A10R4S4'	then	'C1 - Obsolete Location'
when	'C1A10R4S5'	then	'C1 - Obsolete Location'
when	'C1A10R4S6'	then	'C1 - Obsolete Location'
when	'C1A10R5S1'	then	'C1 - Obsolete Location'
when	'C1A10R5S3'	then	'C1 - Obsolete Location'
when	'C1A10R5S4'	then	'C1 - Obsolete Location'
when	'C1A10R5S5'	then	'C1 - Obsolete Location'
when	'C1A10R5S6'	then	'C1 - Obsolete Location'
when	'C1A11R1S1'	then	'C1 - Obsolete Location'
when	'C1A11R1S2'	then	'C1 - Obsolete Location'
when	'C1A11R1S3'	then	'C1 - Obsolete Location'
when	'C1A11R1S4'	then	'C1 - Obsolete Location'
when	'C1A11R1S5'	then	'C1 - Obsolete Location'
when	'C1A11R1S6'	then	'C1 - Obsolete Location'
when	'C1A11R2S2'	then	'C1 - Obsolete Location'
when	'C1A11R2S3'	then	'C1 - Obsolete Location'
when	'C1A11R2S4'	then	'C1 - Obsolete Location'
when	'C1A11R2S5'	then	'C1 - Obsolete Location'
when	'C1A11R2S6'	then	'C1 - Obsolete Location'
when	'C1A12R1G'	then	'C1 - Obsolete Location'
when	'C1A12R1S1'	then	'C1 - Obsolete Location'
when	'C1A12R1S2'	then	'C1 - Obsolete Location'
when	'C1A12R1S3'	then	'C1 - Obsolete Location'
when	'C1A12R1S4'	then	'C1 - Obsolete Location'
when	'C1A12R1S5'	then	'C1 - Obsolete Location'
when	'C1A12R1S6'	then	'C1 - Obsolete Location'
when	'C1A12R2G'	then	'C1 - Obsolete Location'
when	'C1A12R2S1'	then	'C1 - Obsolete Location'
when	'C1A12R2S2'	then	'C1 - Obsolete Location'
when	'C1A12R2S3'	then	'C1 - Obsolete Location'
when	'C1A12R2S4'	then	'C1 - Obsolete Location'
when	'C1A12R2S5'	then	'C1 - Obsolete Location'
when	'C1A13R2S6'	then	'C1 - Obsolete Location'
when	'C1A14R1S1'	then	'C1 - Obsolete Location'
when	'C1A14R1S4'	then	'C1 - Obsolete Location'
when	'C1A14R2S1'	then	'C1 - Obsolete Location'
when	'C1A14R2S2'	then	'C1 - Obsolete Location'
when	'C1A14R2S4'	then	'C1 - Obsolete Location'
when	'C1A14R2S5'	then	'C1 - Obsolete Location'
when	'C1A14R3S4'	then	'C1 - Obsolete Location'
when	'C1A15R1'	then	'C1 - Obsolete Location'
when	'C1A15R2'	then	'C1 - Obsolete Location'
when	'C1A15R2S6'	then	'C1 - Obsolete Location'
when	'C1A16'	then	'C1 - Obsolete Location'
when	'C1A16R1'	then	'C1 - Obsolete Location'
when	'C1A16R1G'	then	'C1 - Obsolete Location'
when	'C1A16R1S1'	then	'C1 - Obsolete Location'
when	'C1A16R1S3'	then	'C1 - Obsolete Location'
when	'C1A16R1S4'	then	'C1 - Obsolete Location'
when	'C1A16R1S5'	then	'C1 - Obsolete Location'
when	'C1A16R1S6'	then	'C1 - Obsolete Location'
when	'C1A16R2'	then	'C1 - Obsolete Location'
when	'C1A16R2G'	then	'C1 - Obsolete Location'
when	'C1A16R2S1'	then	'C1 - Obsolete Location'
when	'C1A16R2S2'	then	'C1 - Obsolete Location'
when	'C1A16R2S3'	then	'C1 - Obsolete Location'
when	'C1A16R2S4'	then	'C1 - Obsolete Location'
when	'C1A16R2S5'	then	'C1 - Obsolete Location'
when	'C1A16R3G'	then	'C1 - Obsolete Location'
when	'C1A16R3S1'	then	'C1 - Obsolete Location'
when	'C1A16R3S2'	then	'C1 - Obsolete Location'
when	'C1A16R3S3'	then	'C1 - Obsolete Location'
when	'C1A16R3S4'	then	'C1 - Obsolete Location'
when	'C1A16R3S5'	then	'C1 - Obsolete Location'
when	'C1A16R4G'	then	'C1 - Obsolete Location'
when	'C1A16R4S1'	then	'C1 - Obsolete Location'
when	'C1A16R4S2'	then	'C1 - Obsolete Location'
when	'C1A16R4S3'	then	'C1 - Obsolete Location'
when	'C1A16R4S4'	then	'C1 - Obsolete Location'
when	'C1A16R4S5'	then	'C1 - Obsolete Location'
when	'C1A16R5G'	then	'C1 - Obsolete Location'
when	'C1A16R5S4'	then	'C1 - Obsolete Location'
when	'C1A16R5S5'	then	'C1 - Obsolete Location'
when	'C1A16R6S4'	then	'C1 - Obsolete Location'
when	'C1A16R6S5'	then	'C1 - Obsolete Location'
when	'C1A16R7S4'	then	'C1 - Obsolete Location'
when	'C1A16R7S5'	then	'C1 - Obsolete Location'
when	'C1A17R1S1'	then	'C1 - Obsolete Location'
when	'C1A18R1S1'	then	'C1 - Obsolete Location'
when	'C1A19R1S1'	then	'C1 - Obsolete Location'
when	'C1A19R1S2'	then	'C1 - Obsolete Location'
when	'C1A19R1S3'	then	'C1 - Obsolete Location'
when	'C1A19R1S4'	then	'C1 - Obsolete Location'
when	'C1A19R1S5'	then	'C1 - Obsolete Location'
when	'C1A1R1S1'	then	'C1 - Obsolete Location'
when	'C1A1R1S2'	then	'C1 - Obsolete Location'
when	'C1A1R1S3'	then	'C1 - Obsolete Location'
when	'C1A1R1S5'	then	'C1 - Obsolete Location'
when	'C1A1R1S6'	then	'C1 - Obsolete Location'
when	'C1A1R1S7'	then	'C1 - Obsolete Location'
when	'C1A1R3S4'	then	'C1 - Obsolete Location'
when	'C1A1R3S5'	then	'C1 - Obsolete Location'
when	'C1A20R1S1'	then	'C1 - Obsolete Location'
when	'C1A20R1S2'	then	'C1 - Obsolete Location'
when	'C1A20R1S3'	then	'C1 - Obsolete Location'
when	'C1A20R1S4'	then	'C1 - Obsolete Location'
when	'C1A20R1S5'	then	'C1 - Obsolete Location'
when	'C1A21R1S5'	then	'C1 - Obsolete Location'
when	'C1A21R5S2'	then	'C1 - Obsolete Location'
when	'C1A22R1S1'	then	'C1 - Obsolete Location'
when	'C1A22R1S2'	then	'C1 - Obsolete Location'
when	'C1A22R1S3'	then	'C1 - Obsolete Location'
when	'C1A22R1S4'	then	'C1 - Obsolete Location'
when	'C1A22R1S5'	then	'C1 - Obsolete Location'
when	'C1A22R2S1'	then	'C1 - Obsolete Location'
when	'C1A22R2S2'	then	'C1 - Obsolete Location'
when	'C1A22R2S3'	then	'C1 - Obsolete Location'
when	'C1A22R2S4'	then	'C1 - Obsolete Location'
when	'C1A22R2S5'	then	'C1 - Obsolete Location'
when	'C1A22R2S6'	then	'C1 - Obsolete Location'
when	'C1A22R3S1'	then	'C1 - Obsolete Location'
when	'C1A22R3S3'	then	'C1 - Obsolete Location'
when	'C1A22R3S4'	then	'C1 - Obsolete Location'
when	'C1A22R3S5'	then	'C1 - Obsolete Location'
when	'C1A22R3S6'	then	'C1 - Obsolete Location'
when	'C1A22R4S2'	then	'C1 - Obsolete Location'
when	'C1A22R4S3'	then	'C1 - Obsolete Location'
when	'C1A22R4S4'	then	'C1 - Obsolete Location'
when	'C1A2R1S1'	then	'C1 - Obsolete Location'
when	'C1A2R1S2'	then	'C1 - Obsolete Location'
when	'C1A2R1S3'	then	'C1 - Obsolete Location'
when	'C1A2R1S4'	then	'C1 - Obsolete Location'
when	'C1A2R1S5'	then	'C1 - Obsolete Location'
when	'C1A2R1S6'	then	'C1 - Obsolete Location'
when	'C1A2R1S7'	then	'C1 - Obsolete Location'
when	'C1A2R2G'	then	'C1 - Obsolete Location'
when	'C1A2R2S1'	then	'C1 - Obsolete Location'
when	'C1A2R2S2'	then	'C1 - Obsolete Location'
when	'C1A2R2S3'	then	'C1 - Obsolete Location'
when	'C1A2R2S5'	then	'C1 - Obsolete Location'
when	'C1A3R1S1'	then	'C1 - Obsolete Location'
when	'C1A3R1S2'	then	'C1 - Obsolete Location'
when	'C1A3R1S3'	then	'C1 - Obsolete Location'
when	'C1A3R1S4'	then	'C1 - Obsolete Location'
when	'C1A3R1S5'	then	'C1 - Obsolete Location'
when	'C1A3R1S6'	then	'C1 - Obsolete Location'
when	'C1A3R1S7'	then	'C1 - Obsolete Location'
when	'C1A3R2S1'	then	'C1 - Obsolete Location'
when	'C1A3R2S2'	then	'C1 - Obsolete Location'
when	'C1A3R2S3'	then	'C1 - Obsolete Location'
when	'C1A3R2S4'	then	'C1 - Obsolete Location'
when	'C1A3R2S5'	then	'C1 - Obsolete Location'
when	'C1A3R2S6'	then	'C1 - Obsolete Location'
when	'C1A3R2S7'	then	'C1 - Obsolete Location'
when	'C1A4R1S1'	then	'C1 - Obsolete Location'
when	'C1A4R1S2'	then	'C1 - Obsolete Location'
when	'C1A4R1S3'	then	'C1 - Obsolete Location'
when	'C1A4R1S4'	then	'C1 - Obsolete Location'
when	'C1A4R1S5'	then	'C1 - Obsolete Location'
when	'C1A4R1S6'	then	'C1 - Obsolete Location'
when	'C1A4R1S7'	then	'C1 - Obsolete Location'
when	'C1A4R2S1'	then	'C1 - Obsolete Location'
when	'C1A4R2S2'	then	'C1 - Obsolete Location'
when	'C1A4R2S3'	then	'C1 - Obsolete Location'
when	'C1A4R2S4'	then	'C1 - Obsolete Location'
when	'C1A4R2S5'	then	'C1 - Obsolete Location'
when	'C1A4R2S6'	then	'C1 - Obsolete Location'
when	'C1A4R2S7'	then	'C1 - Obsolete Location'
when	'C1A5R1S1'	then	'C1 - Obsolete Location'
when	'C1A5R1S2'	then	'C1 - Obsolete Location'
when	'C1A5R1S3'	then	'C1 - Obsolete Location'
when	'C1A5R1S4'	then	'C1 - Obsolete Location'
when	'C1A5R1S5'	then	'C1 - Obsolete Location'
when	'C1A5R1S6'	then	'C1 - Obsolete Location'
when	'C1A5R1S7'	then	'C1 - Obsolete Location'
when	'C1A5R2S1'	then	'C1 - Obsolete Location'
when	'C1A5R2S2'	then	'C1 - Obsolete Location'
when	'C1A5R2S3'	then	'C1 - Obsolete Location'
when	'C1A5R2S4'	then	'C1 - Obsolete Location'
when	'C1A5R2S5'	then	'C1 - Obsolete Location'
when	'C1A5R2S6'	then	'C1 - Obsolete Location'
when	'C1A5R2S7'	then	'C1 - Obsolete Location'
when	'C1A6R1S1'	then	'C1 - Obsolete Location'
when	'C1A6R1S2'	then	'C1 - Obsolete Location'
when	'C1A6R1S3'	then	'C1 - Obsolete Location'
when	'C1A6R1S4'	then	'C1 - Obsolete Location'
when	'C1A6R1S5'	then	'C1 - Obsolete Location'
when	'C1A6R2S1'	then	'C1 - Obsolete Location'
when	'C1A6R2S2'	then	'C1 - Obsolete Location'
when	'C1A6R2S3'	then	'C1 - Obsolete Location'
when	'C1A6R2S4'	then	'C1 - Obsolete Location'
when	'C1A6R2S5'	then	'C1 - Obsolete Location'
when	'C1A6R2S6'	then	'C1 - Obsolete Location'
when	'C1A6R2S7'	then	'C1 - Obsolete Location'
when	'C1A7R1G'	then	'C1 - Obsolete Location'
when	'C1A7R1S1'	then	'C1 - Obsolete Location'
when	'C1A7R1S2'	then	'C1 - Obsolete Location'
when	'C1A7R1S4'	then	'C1 - Obsolete Location'
when	'C1A7R2S1'	then	'C1 - Obsolete Location'
when	'C1A7R2S2'	then	'C1 - Obsolete Location'
when	'C1A7R2S3'	then	'C1 - Obsolete Location'
when	'C1A7R2S4'	then	'C1 - Obsolete Location'
when	'C1A7R2S5'	then	'C1 - Obsolete Location'
when	'C1A8R1S1'	then	'C1 - Obsolete Location'
when	'C1A8R1S2'	then	'C1 - Obsolete Location'
when	'C1A8R1S3'	then	'C1 - Obsolete Location'
when	'C1A8R1S4'	then	'C1 - Obsolete Location'
when	'C1A8R1S5'	then	'C1 - Obsolete Location'
when	'C1A8R2S1'	then	'C1 - Obsolete Location'
when	'C1A8R2S2'	then	'C1 - Obsolete Location'
when	'C1A8R2S5'	then	'C1 - Obsolete Location'
when	'C1A9R1G'	then	'C1 - Obsolete Location'
when	'C1A9R1S1'	then	'C1 - Obsolete Location'
when	'C1A9R1S2'	then	'C1 - Obsolete Location'
when	'C1A9R1S3'	then	'C1 - Obsolete Location'
when	'C1A9R1S4'	then	'C1 - Obsolete Location'
when	'C1A9R1S5'	then	'C1 - Obsolete Location'
when	'C1A9R1S6'	then	'C1 - Obsolete Location'
when	'C1A9R2S2'	then	'C1 - Obsolete Location'
when	'C1A9R2S3'	then	'C1 - Obsolete Location'
when	'C1A9R2S4'	then	'C1 - Obsolete Location'
when	'C1A9R2S5'	then	'C1 - Obsolete Location'
when	'C1A9R2S6'	then	'C1 - Obsolete Location'
when	'C1-AMMOSHELF'	then	'C1 - Obsolete Location'
when	'C1E1'	then	'C1 - Obsolete Location'
when	'C1E2'	then	'C1 - Obsolete Location'
when	'C1E3'	then	'C1 - Obsolete Location'
when	'C1E4'	then	'C1 - Obsolete Location'
when	'C1E5'	then	'C1 - Obsolete Location'
when	'C1E6'	then	'C1 - Obsolete Location'
when	'C1-PALLETRACKIN'	then	'C1 - Obsolete Location'
when	'C1-RECSTAGING'	then	'C1 - Obsolete Location'
when	'C1-SAFE1'	then	'C1 - Obsolete Location'
when	'C2'	then	'Shipping Cage'
when	'C2R1G'	then	'Shipping Cage'
when	'C2R2S3'	then	'Shipping Cage'
when	'C3'	then	'Shipping Cage'
when	'C4A1R1G'	then	'C4 - Obsolete Location'
when	'C4A1R1S1'	then	'C4 - Obsolete Location'
when	'C4A1R1S3'	then	'C4 - Obsolete Location'
when	'C4A1R2S3'	then	'C4 - Obsolete Location'
when	'CMA10R1S1'	then	'Cage Main'
when	'CMA10R1S2'	then	'Cage Main'
when	'CMA10R1S3'	then	'Cage Main'
when	'CMA10R1S4'	then	'Cage Main'
when	'CMA10R1S5'	then	'Cage Main'
when	'CMA10R1S6'	then	'Cage Main'
when	'CMA10R1SF'	then	'Cage Main'
when	'CMA10R2S1'	then	'Cage Main'
when	'CMA10R2S2'	then	'Cage Main'
when	'CMA10R2S3'	then	'Cage Main'
when	'CMA10R2S4'	then	'Cage Main'
when	'CMA10R2S5'	then	'Cage Main'
when	'CMA10R2S6'	then	'Cage Main'
when	'CMA10R2SF'	then	'Cage Main'
when	'CMA10R3S6'	then	'Cage Main'
when	'CMA10R4SF'	then	'Cage Main'
when	'CMA10R5S6'	then	'Cage Main'
when	'CMA10R5SF'	then	'Cage Main'
when	'CMA11R1S1'	then	'Cage Main'
when	'CMA11R1S2'	then	'Cage Main'
when	'CMA11R1S3'	then	'Cage Main'
when	'CMA11R1S4'	then	'Cage Main'
when	'CMA11R1S5'	then	'Cage Main'
when	'CMA11R1S6'	then	'Cage Main'
when	'CMA11R1SF'	then	'Cage Main'
when	'CMA11R2S1'	then	'Cage Main'
when	'CMA11R2S2'	then	'Cage Main'
when	'CMA11R2S3'	then	'Cage Main'
when	'CMA11R2S4'	then	'Cage Main'
when	'CMA11R2S5'	then	'Cage Main'
when	'CMA11R2S6'	then	'Cage Main'
when	'CMA11R3S1'	then	'Cage Main'
when	'CMA11R3S2'	then	'Cage Main'
when	'CMA11R3S3'	then	'Cage Main'
when	'CMA11R4S1'	then	'Cage Main'
when	'CMA11R4S2'	then	'Cage Main'
when	'CMA11R4S3'	then	'Cage Main'
when	'CMA11R4S4'	then	'Cage Main'
when	'CMA11R4SF'	then	'Cage Main'
when	'CMA11R5S1'	then	'Cage Main'
when	'CMA11R5S2'	then	'Cage Main'
when	'CMA11R5S3'	then	'Cage Main'
when	'CMA11R5S4'	then	'Cage Main'
when	'CMA11R5S5'	then	'Cage Main'
when	'CMA11R5S6'	then	'Cage Main'
when	'CMA11R5SF'	then	'Cage Main'
when	'CMA12R1S1'	then	'Cage Main'
when	'CMA12R1S2'	then	'Cage Main'
when	'CMA12R1S3'	then	'Cage Main'
when	'CMA12R1S5'	then	'Cage Main'
when	'CMA12R1S6'	then	'Cage Main'
when	'CMA12R2S1'	then	'Cage Main'
when	'CMA12R2S2'	then	'Cage Main'
when	'CMA12R2S3'	then	'Cage Main'
when	'CMA12R2S4'	then	'Cage Main'
when	'CMA12R2S5'	then	'Cage Main'
when	'CMA12R3S1'	then	'Cage Main'
when	'CMA12R3S2'	then	'Cage Main'
when	'CMA12R3S3'	then	'Cage Main'
when	'CMA12R3S4'	then	'Cage Main'
when	'CMA12R3S5'	then	'Cage Main'
when	'CMA12R3S6'	then	'Cage Main'
when	'CMA12R3SF'	then	'Cage Main'
when	'CMA12R4S1'	then	'Cage Main'
when	'CMA12R4S2'	then	'Cage Main'
when	'CMA12R4S3'	then	'Cage Main'
when	'CMA12R4S4'	then	'Cage Main'
when	'CMA12R4S5'	then	'Cage Main'
when	'CMA12R4S6'	then	'Cage Main'
when	'CMA12R4SF'	then	'Cage Main'
when	'CMA12R5S1'	then	'Cage Main'
when	'CMA12R5S3'	then	'Cage Main'
when	'CMA12R5S4'	then	'Cage Main'
when	'CMA12R5S5'	then	'Cage Main'
when	'CMA1R1S1'	then	'Cage Main'
when	'CMA1R1S2'	then	'Cage Main'
when	'CMA1R1S3'	then	'Cage Main'
when	'CMA1R1S5'	then	'Cage Main'
when	'CMA1R1S8'	then	'Cage Main'
when	'CMA1R1S9'	then	'Cage Main'
when	'CMA1R1SF'	then	'Cage Main'
when	'CMA1R2S2'	then	'Cage Main'
when	'CMA1R2S3'	then	'Cage Main'
when	'CMA1R2S7'	then	'Cage Main'
when	'CMA1R2S8'	then	'Cage Main'
when	'CMA1R2S9'	then	'Cage Main'
when	'CMA1R2SF'	then	'Cage Main'
when	'CMA1R3S1'	then	'Cage Main'
when	'CMA1R3S2'	then	'Cage Main'
when	'CMA1R3S3'	then	'Cage Main'
when	'CMA1R3S4'	then	'Cage Main'
when	'CMA1R3S5'	then	'Cage Main'
when	'CMA1R3S6'	then	'Cage Main'
when	'CMA1R3SF'	then	'Cage Main'
when	'CMA1R4S1'	then	'Cage Main'
when	'CMA1R4S2'	then	'Cage Main'
when	'CMA1R4S3'	then	'Cage Main'
when	'CMA1R4S4'	then	'Cage Main'
when	'CMA1R4S5'	then	'Cage Main'
when	'CMA1R4SF'	then	'Cage Main'
when	'CMA2R1S1'	then	'Cage Main'
when	'CMA2R1S2'	then	'Cage Main'
when	'CMA2R1S3'	then	'Cage Main'
when	'CMA2R1S4'	then	'Cage Main'
when	'CMA2R1S5'	then	'Cage Main'
when	'CMA2R1S6'	then	'Cage Main'
when	'CMA2R1S7'	then	'Cage Main'
when	'CMA2R1S8'	then	'Cage Main'
when	'CMA2R1S9'	then	'Cage Main'
when	'CMA2R1SF'	then	'Cage Main'
when	'CMA2R2S1'	then	'Cage Main'
when	'CMA2R2S2'	then	'Cage Main'
when	'CMA2R2S3'	then	'Cage Main'
when	'CMA2R2S4'	then	'Cage Main'
when	'CMA2R2S5'	then	'Cage Main'
when	'CMA2R2S6'	then	'Cage Main'
when	'CMA2R2S7'	then	'Cage Main'
when	'CMA2R2S8'	then	'Cage Main'
when	'CMA2R2S9'	then	'Cage Main'
when	'CMA2R3S1'	then	'Cage Main'
when	'CMA2R3S2'	then	'Cage Main'
when	'CMA2R3S3'	then	'Cage Main'
when	'CMA2R3S4'	then	'Cage Main'
when	'CMA2R3S5'	then	'Cage Main'
when	'CMA2R3S6'	then	'Cage Main'
when	'CMA2R3SF'	then	'Cage Main'
when	'CMA2R4S1'	then	'Cage Main'
when	'CMA2R4S2'	then	'Cage Main'
when	'CMA2R4S3'	then	'Cage Main'
when	'CMA2R4S5'	then	'Cage Main'
when	'CMA2R4S6'	then	'Cage Main'
when	'CMA2R4SF'	then	'Cage Main'
when	'CMA3R1S1'	then	'Cage Main'
when	'CMA3R1S2'	then	'Cage Main'
when	'CMA3R1S3'	then	'Cage Main'
when	'CMA3R1S4'	then	'Cage Main'
when	'CMA3R1S5'	then	'Cage Main'
when	'CMA3R1S6'	then	'Cage Main'
when	'CMA3R2S1'	then	'Cage Main'
when	'CMA3R2S2'	then	'Cage Main'
when	'CMA3R2S3'	then	'Cage Main'
when	'CMA3R2S4'	then	'Cage Main'
when	'CMA3R2S5'	then	'Cage Main'
when	'CMA3R2S6'	then	'Cage Main'
when	'CMA3R2SF'	then	'Cage Main'
when	'CMA3R3S1'	then	'Cage Main'
when	'CMA3R3S2'	then	'Cage Main'
when	'CMA3R3S3'	then	'Cage Main'
when	'CMA3R3S6'	then	'Cage Main'
when	'CMA3R3SF'	then	'Cage Main'
when	'CMA3R4S1'	then	'Cage Main'
when	'CMA3R4S2'	then	'Cage Main'
when	'CMA3R4S3'	then	'Cage Main'
when	'CMA3R4S4'	then	'Cage Main'
when	'CMA3R4S5'	then	'Cage Main'
when	'CMA3R4S6'	then	'Cage Main'
when	'CMA4R1S1'	then	'Cage Main'
when	'CMA4R1S2'	then	'Cage Main'
when	'CMA4R1S3'	then	'Cage Main'
when	'CMA4R1S4'	then	'Cage Main'
when	'CMA4R1S5'	then	'Cage Main'
when	'CMA4R1S6'	then	'Cage Main'
when	'CMA4R1SF'	then	'Cage Main'
when	'CMA4R2S1'	then	'Cage Main'
when	'CMA4R2S2'	then	'Cage Main'
when	'CMA4R2S3'	then	'Cage Main'
when	'CMA4R2S4'	then	'Cage Main'
when	'CMA4R2S5'	then	'Cage Main'
when	'CMA4R2S6'	then	'Cage Main'
when	'CMA4R2SF'	then	'Cage Main'
when	'CMA4R3S1'	then	'Cage Main'
when	'CMA4R3S2'	then	'Cage Main'
when	'CMA4R3S3'	then	'Cage Main'
when	'CMA4R3S4'	then	'Cage Main'
when	'CMA4R3S5'	then	'Cage Main'
when	'CMA4R3S6'	then	'Cage Main'
when	'CMA4R3SF'	then	'Cage Main'
when	'CMA4R4S1'	then	'Cage Main'
when	'CMA4R4S2'	then	'Cage Main'
when	'CMA4R4S3'	then	'Cage Main'
when	'CMA4R4S4'	then	'Cage Main'
when	'CMA4R4S5'	then	'Cage Main'
when	'CMA4R4S6'	then	'Cage Main'
when	'CMA4R4SF'	then	'Cage Main'
when	'CMA5R1S2'	then	'Cage Main'
when	'CMA5R1S3'	then	'Cage Main'
when	'CMA5R1S4'	then	'Cage Main'
when	'CMA5R1S5'	then	'Cage Main'
when	'CMA5R1S6'	then	'Cage Main'
when	'CMA5R1SF'	then	'Cage Main'
when	'CMA5R2S1'	then	'Cage Main'
when	'CMA5R2S2'	then	'Cage Main'
when	'CMA5R2S3'	then	'Cage Main'
when	'CMA5R2S4'	then	'Cage Main'
when	'CMA5R2S5'	then	'Cage Main'
when	'CMA5R2S6'	then	'Cage Main'
when	'CMA5R2SF'	then	'Cage Main'
when	'CMA5R3S1'	then	'Cage Main'
when	'CMA5R3S2'	then	'Cage Main'
when	'CMA5R3S3'	then	'Cage Main'
when	'CMA5R3S4'	then	'Cage Main'
when	'CMA5R3S5'	then	'Cage Main'
when	'CMA5R3S6'	then	'Cage Main'
when	'CMA5R3SF'	then	'Cage Main'
when	'CMA5R4S1'	then	'Cage Main'
when	'CMA5R4S6'	then	'Cage Main'
when	'CMA5R4SF'	then	'Cage Main'
when	'CMA6R1S1'	then	'Cage Main'
when	'CMA6R1S2'	then	'Cage Main'
when	'CMA6R1S3'	then	'Cage Main'
when	'CMA6R1S4'	then	'Cage Main'
when	'CMA6R1S5'	then	'Cage Main'
when	'CMA6R1S6'	then	'Cage Main'
when	'CMA6R2S1'	then	'Cage Main'
when	'CMA6R2S2'	then	'Cage Main'
when	'CMA6R2S3'	then	'Cage Main'
when	'CMA6R2S4'	then	'Cage Main'
when	'CMA6R2S5'	then	'Cage Main'
when	'CMA6R2S6'	then	'Cage Main'
when	'CMA6R3S1'	then	'Cage Main'
when	'CMA6R3S2'	then	'Cage Main'
when	'CMA6R3S3'	then	'Cage Main'
when	'CMA6R3S4'	then	'Cage Main'
when	'CMA6R3S5'	then	'Cage Main'
when	'CMA6R3S6'	then	'Cage Main'
when	'CMA6R4S1'	then	'Cage Main'
when	'CMA6R4S2'	then	'Cage Main'
when	'CMA6R4S3'	then	'Cage Main'
when	'CMA6R4S4'	then	'Cage Main'
when	'CMA6R4S5'	then	'Cage Main'
when	'CMA6R4S6'	then	'Cage Main'
when	'CMA7R1S1'	then	'Cage Main'
when	'CMA7R1S2'	then	'Cage Main'
when	'CMA7R1S3'	then	'Cage Main'
when	'CMA7R1S4'	then	'Cage Main'
when	'CMA7R1S5'	then	'Cage Main'
when	'CMA7R1S6'	then	'Cage Main'
when	'CMA7R1SF'	then	'Cage Main'
when	'CMA7R2S1'	then	'Cage Main'
when	'CMA7R2S2'	then	'Cage Main'
when	'CMA7R2S3'	then	'Cage Main'
when	'CMA7R2S4'	then	'Cage Main'
when	'CMA7R2S5'	then	'Cage Main'
when	'CMA7R2S6'	then	'Cage Main'
when	'CMA7R2SF'	then	'Cage Main'
when	'CMA7R3S1'	then	'Cage Main'
when	'CMA7R3S2'	then	'Cage Main'
when	'CMA7R3S3'	then	'Cage Main'
when	'CMA7R3S4'	then	'Cage Main'
when	'CMA7R3S5'	then	'Cage Main'
when	'CMA7R3S6'	then	'Cage Main'
when	'CMA7R3SF'	then	'Cage Main'
when	'CMA7R4S1'	then	'Cage Main'
when	'CMA7R4S2'	then	'Cage Main'
when	'CMA7R4S3'	then	'Cage Main'
when	'CMA7R4S4'	then	'Cage Main'
when	'CMA7R4S5'	then	'Cage Main'
when	'CMA7R4S6'	then	'Cage Main'
when	'CMA7R4SF'	then	'Cage Main'
when	'CMA8R1S1'	then	'Cage Main'
when	'CMA8R1S2'	then	'Cage Main'
when	'CMA8R1S3'	then	'Cage Main'
when	'CMA8R1S4'	then	'Cage Main'
when	'CMA8R1S5'	then	'Cage Main'
when	'CMA8R1S6'	then	'Cage Main'
when	'CMA8R1SF'	then	'Cage Main'
when	'CMA8R2S1'	then	'Cage Main'
when	'CMA8R2S2'	then	'Cage Main'
when	'CMA8R2S3'	then	'Cage Main'
when	'CMA8R2S4'	then	'Cage Main'
when	'CMA8R2S5'	then	'Cage Main'
when	'CMA8R2S6'	then	'Cage Main'
when	'CMA8R2SF'	then	'Cage Main'
when	'CMA8R3S1'	then	'Cage Main'
when	'CMA8R3S2'	then	'Cage Main'
when	'CMA8R3S3'	then	'Cage Main'
when	'CMA8R3S4'	then	'Cage Main'
when	'CMA8R3S5'	then	'Cage Main'
when	'CMA8R3S6'	then	'Cage Main'
when	'CMA8R3SF'	then	'Cage Main'
when	'CMA8R4S1'	then	'Cage Main'
when	'CMA8R4S2'	then	'Cage Main'
when	'CMA8R4S3'	then	'Cage Main'
when	'CMA8R4S4'	then	'Cage Main'
when	'CMA8R4S5'	then	'Cage Main'
when	'CMA8R4S6'	then	'Cage Main'
when	'CMA8R4SF'	then	'Cage Main'
when	'CMA9R1S1'	then	'Cage Main'
when	'CMA9R1S2'	then	'Cage Main'
when	'CMA9R1S3'	then	'Cage Main'
when	'CMA9R1S4'	then	'Cage Main'
when	'CMA9R1S5'	then	'Cage Main'
when	'CMA9R1S6'	then	'Cage Main'
when	'CMA9R1SF'	then	'Cage Main'
when	'CMA9R2S1'	then	'Cage Main'
when	'CMA9R2S2'	then	'Cage Main'
when	'CMA9R2S3'	then	'Cage Main'
when	'CMA9R2S4'	then	'Cage Main'
when	'CMA9R2S5'	then	'Cage Main'
when	'CMA9R2S6'	then	'Cage Main'
when	'CMA9R2SF'	then	'Cage Main'
when	'CMA9R3S1'	then	'Cage Main'
when	'CMA9R3S2'	then	'Cage Main'
when	'CMA9R3S3'	then	'Cage Main'
when	'CMA9R3S4'	then	'Cage Main'
when	'CMA9R3S5'	then	'Cage Main'
when	'CMA9R3S6'	then	'Cage Main'
when	'CMA9R3SF'	then	'Cage Main'
when	'CMA9R4S1'	then	'Cage Main'
when	'CMA9R4S2'	then	'Cage Main'
when	'CMA9R4S3'	then	'Cage Main'
when	'CMA9R4S4'	then	'Cage Main'
when	'CMA9R4S5'	then	'Cage Main'
when	'CMA9R4S6'	then	'Cage Main'
when	'CMA9R4SF'	then	'Cage Main'
when	'CMA9R5S1'	then	'Cage Main'
when	'CMA9R5S2'	then	'Cage Main'
when	'CMA9R5S3'	then	'Cage Main'
when	'CMA9R5S4'	then	'Cage Main'
when	'CMA9R5S5'	then	'Cage Main'
when	'CMA9R5S6'	then	'Cage Main'
when	'CMA9R5SF'	then	'Cage Main'
when	'CVM'	then	'Obsolete'
when	'D2'	then	'Raw Metals'
when	'ENGINEERING'	then	'Engineering'
when	'F1'	then	'Cut Freezer'
when	'FLOOR'	then	'WIP'
when	'FREEZER'	then	'Cut Freezer'
when	'FREEZER-A'	then	'Outdoor Freezers'
when	'FREEZER-BIG'	then	'Outdoor Freezers'
when	'FREEZER-SMALL'	then	'Outdoor Freezers'
when	'GUNROOM'	then	'Loft 3'
when	'L1'	then	'Loft 1'
when	'L3'	then	'Loft 3'
when	'L3AB'	then	'Loft 3'
when	'L4'	then	'Loft 4'
when	'MACHINESHOP'	then	'WIP'
when	'MAIN'	then	'C1 - Obsolete Location'
when	'MARKETING'	then	'Marketing - Obsolete Location'
when	'MCNALLY'	then	'Obsolete'
when	'M-RACK'	then	'Raw Metals'
when	'MRB AREA'	then	'MRB'
when	'P-ASSY'	then	'WIP'
when	'P-ASSY-GUN'	then	'WIP'
when	'P-BBL'	then	'WIP'
when	'P-BBL-R1G'	then	'WIP'
when	'P-BBL-R1S2'	then	'WIP'
when	'P-BBL-R2S1'	then	'WIP'
when	'P-BBL-R3S2'	then	'WIP'
when	'P-BBL-R4S3'	then	'WIP'
when	'P-BBL-R5S1'	then	'WIP'
when	'P-COMP'	then	'WIP'
when	'P-COMP-R2S2'	then	'WIP'
when	'P-COMP-R3S4'	then	'WIP'
when	'P-COMP-R4S4'	then	'WIP'
when	'P-ENGRAVING'	then	'WIP'
when	'P-EPHRAIM'	then	'WIP'
when	'P-MS'	then	'WIP'
when	'P-MS-R1S1'	then	'WIP'
when	'P-MS-R1S2'	then	'WIP'
when	'P-MS-R1S3'	then	'WIP'
when	'P-MS-R2G'	then	'WIP'
when	'P-MS-R2S0'	then	'WIP'
when	'P-MS-R2S1'	then	'WIP'
when	'P-MS-R2S2'	then	'WIP'
when	'P-MS-R2S4'	then	'WIP'
when	'P-MS-R3G'	then	'WIP'
when	'P-MS-R3S0'	then	'WIP'
when	'P-MS-R3S1'	then	'WIP'
when	'P-MS-R3S3'	then	'WIP'
when	'P-MS-R4S0'	then	'WIP'
when	'P-MS-R4S1'	then	'WIP'
when	'P-MS-R4S2'	then	'WIP'
when	'P-MS-R4S3'	then	'WIP'
when	'P-MS-R5G'	then	'WIP'
when	'P-MS-R5S1'	then	'WIP'
when	'P-MS-R5S2'	then	'WIP'
when	'P-MS-R5S3'	then	'WIP'
when	'P-MS-T1B0'	then	'WIP'
when	'P-MS-T1B4'	then	'WIP'
when	'P-MS-T1B5'	then	'WIP'
when	'P-MS-T1B6'	then	'WIP'
when	'P-MS-T1B7'	then	'WIP'
when	'P-MS-T1B8'	then	'WIP'
when	'P-MS-WLD'	then	'WIP'
when	'P-PNT1'	then	'WIP'
when	'P-PNT2'	then	'WIP'
when	'P-POLISH'	then	'WIP'
when	'P-SAND'	then	'WIP'
when	'P-SASSY'	then	'WIP'
when	'P-STOCK'	then	'WIP'
when	'P-WRAP'	then	'WIP'
when	'R&D BOX'	then	'Loft 3'
when	'RCA2R1S2'	then	'Receiving Cage'
when	'RCA2R1S3'	then	'Receiving Cage'
when	'RCA2R1S5'	then	'Receiving Cage'
when	'RCA2R2S1'	then	'Receiving Cage'
when	'RCA2R2S2'	then	'Receiving Cage'
when	'RCA2R2S3'	then	'Receiving Cage'
when	'RCBR'	then	'Receiving Cage'
when	'RECEIVING'	then	'Receiving Cage'
when	'RECVINSP'	then	'MRB'
when	'STAGING'	then	'Receiving Cage'
when	'STORES'	then	'C1 - Obsolete Location'
when	'WEBSTORE'	then	'Webstore-Obsolete'
when	'XFER'	then	'Xfer'
else 'Unmapped' end as Area




from(
SELECT
ISNULL((cost.act_material_cost+cost.act_labor_cost+cost.act_service_cost)/cost.Qty,0) as Average_Cost,
cost.Qty as Qty,
Cost.Part_ID

from (

select
sum(case inventory_trans.type when 'I' then INVENTORY_TRANS.ACT_MATERIAL_COST else -INVENTORY_TRANS.ACT_MATERIAL_COST end) as Act_Material_Cost,
sum(case inventory_trans.type when 'I' then INVENTORY_TRANS.ACT_LABOR_COST else -INVENTORY_TRANS.ACT_LABOR_COST end) as ACT_LABOR_COST,
sum(case inventory_trans.type when 'I' then INVENTORY_TRANS.ACT_BURDEN_COST else -INVENTORY_TRANS.ACT_BURDEN_COST end) as ACT_BURDEN_COST,
sum(case inventory_trans.type when 'I' then INVENTORY_TRANS.ACT_SERVICE_COST else -INVENTORY_TRANS.ACT_SERVICE_COST end) as ACT_SERVICE_COST,
sum(case inventory_trans.type when 'I' then Inventory_trans.Qty else -inventory_trans.Qty end) as Qty,
Inventory_trans.part_id

from VECA.dbo.INVENTORY_TRANS INVENTORY_TRANS
where Inventory_trans.Part_id is not null 

group by Inventory_trans.part_id) as Cost

where cost.QTY <> 0) as Cost

inner join VECA.dbo.PART_LOCATION PART_LOCATION on Cost.Part_ID = PART_LOCATION.PART_ID
inner join VECA.dbo.part part on part.id = Cost.Part_ID

Where PART_LOCATION.PART_ID = ?

