select 

Dpt.EMPLOYEE_ID,
Dpt.DATE_EFFECTIVE, 
Dpt.DEPARTMENT_ID
from(


SELECT 
LABOR_EMPLOYEE_DEPARTMENT.EMPLOYEE_ID,
LABOR_EMPLOYEE_DEPARTMENT.DATE_EFFECTIVE, 
LABOR_EMPLOYEE_DEPARTMENT.DEPARTMENT_ID,
Row_Number() over (PARTITION by LABOR_EMPLOYEE_DEPARTMENT.EMPLOYEE_ID order by LABOR_EMPLOYEE_DEPARTMENT.DATE_EFFECTIVE desc) as max_thing

FROM VTA.dbo.LABOR_EMPLOYEE_DEPARTMENT LABOR_EMPLOYEE_DEPARTMENT) as Dpt

where Dpt.Max_Thing = 1


---THIS IS THE MAX LABOR STUFF
select
pay.Employee_ID,
pay.Date_Effective,
pay.Base_Pay_Rate

from(

SELECT 
LABOR_EMPLOYEE_PAY_RATE.EMPLOYEE_ID, 
LABOR_EMPLOYEE_PAY_RATE.DATE_EFFECTIVE, 
LABOR_EMPLOYEE_PAY_RATE.BASE_PAY_RATE,
Row_Number() over (PARTITION by LABOR_EMPLOYEE_PAY_RATE.EMPLOYEE_ID order by LABOR_EMPLOYEE_PAY_RATE.DATE_EFFECTIVE desc) as max_thing

FROM VTA.dbo.LABOR_EMPLOYEE_PAY_RATE LABOR_EMPLOYEE_PAY_RATE) as pay
ORDER BY LABOR_EMPLOYEE_PAY_RATE.EMPLOYEE_ID

where pay.max_thing = 1
