services:
  mcp-server:
    build:
      context: ./app
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      MCP_TRANSPORT: streamable-http
      MCP_HOST: 0.0.0.0
      MCP_PORT: "8000"
    ports:
      - "8000:8000"
    volumes:
      - ../queries:/app/src/queries:ro
      - ../database_scripts:/app/src/database_scripts:ro
    command: python main.py
