SELECT 
    DB_NAME() AS [DATABASE],
    NAME AS [FILENAME],
    TYPE_DESC,
    SIZE/128.0 AS [CURRENT_SIZE_MB],
    SIZE/128.0 - CAST(FILEPROPERTY(NAME, 'SPACEUSED') AS INT)/128.0 AS [FREE_SPACE_MB]
FROM SYS.DATABASE_FILES
WHERE TYPE IN (0,1);

SELECT 
    DB_NAME(database_id) AS [DATABASE],
    NAME AS [FILENAME],
    TYPE_DESC,
    SIZE/128.0 AS [CURRENT_SIZE_MB],
    SIZE/128.0 - CAST(FILEPROPERTY(NAME, 'SPACEUSED') AS INT)/128.0 AS [FREE_SPACE_MB]
FROM SYS.MASTER_FILES
WHERE TYPE IN (0,1);