/*
================================================================================
  GL POSTING TODAY - Daily Posting Audit Query
================================================================================
  Shows what posted today (or any specified date) across both VECA and VFIN,
  with summary and detail sections.

  Change @AsOfDate to audit a different day.
  Set @PostedOnly = 1 to exclude unposted VECA distributions.

  @DedupeMode options (mirrors gl_posting_map.sql):
    'HYBRID'  = All VECA rows + VFIN rows that are NOT Exchange-sourced
                (REFERENCE NOT LIKE 'USD%'). Recommended default - avoids
                double-counting VECA detail against Exchange-pushed VFIN
                batches for the same day.
    'VFIN'    = VFIN dists only (GL view; manufacturing as batch summaries)
    'VECA'    = VECA dists only (operational detail view)
    'NONE'    = Everything - WILL double-count on days where Exchange has
                already echoed VECA activity into VFIN. Use to audit the
                Exchange push itself.
================================================================================
*/

DECLARE @AsOfDate     date         = CAST(GETDATE() AS date);  -- Change to specific date as needed
DECLARE @PostedOnly   bit          = 1;             -- 1 = posted only, 0 = include unposted
DECLARE @DedupeMode   nvarchar(10) = 'HYBRID';      -- 'HYBRID'|'VFIN'|'VECA'|'NONE'
DECLARE @ExchangeMark nvarchar(40) = 'USD%';        -- LIKE pattern in VFIN REFERENCE for Exchange-sourced rows

/*
--------------------------------------------------------------------------------
  SECTION 1: Summary by Journal Type
  Quick overview of what posted today and how much.
--------------------------------------------------------------------------------
*/
SELECT
    SOURCE_DB,
    JOURNAL_TYPE,
    COUNT(*)                     AS ROW_COUNT,
    COUNT(DISTINCT COALESCE(DOCUMENT_ID, WO_BASE_ID)) AS DOC_COUNT,
    ROUND(SUM(DEBIT_AMOUNT), 2)  AS TOTAL_DEBITS,
    ROUND(SUM(CREDIT_AMOUNT), 2) AS TOTAL_CREDITS,
    ROUND(SUM(NET_AMOUNT), 2)    AS NET_AMOUNT
FROM (
    -- VECA: WIP Issue
    SELECT 'VECA' AS SOURCE_DB, 'VECA_WIP_ISSUE' AS JOURNAL_TYPE,
        NULL AS DOCUMENT_ID, WORKORDER_BASE_ID AS WO_BASE_ID,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END AS DEBIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END AS CREDIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END AS NET_AMOUNT,
        POSTING_STATUS
    FROM VECA.dbo.WIP_ISSUE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: WIP Receipt
    SELECT 'VECA', 'VECA_WIP_RCPT', NULL, WORKORDER_BASE_ID,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.WIP_RECEIPT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Shipment
    SELECT 'VECA', 'VECA_SHIPMENT', CUST_ORDER_ID, NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.SHIPMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Receivable
    SELECT 'VECA', 'VECA_RECV', INVOICE_ID, NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.RECEIVABLE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Purchase
    SELECT 'VECA', 'VECA_PURCHASE', PURC_ORDER_ID, NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.PURCHASE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Adjustment
    SELECT 'VECA', 'VECA_ADJUST', CAST(TRANSACTION_ID AS nvarchar(30)), NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.ADJUSTMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Indirect
    SELECT 'VECA', 'VECA_INDIRECT', CAST(TRANSACTION_ID AS nvarchar(30)), NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.INDIRECT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: General Journal
    SELECT 'VECA', 'VECA_GJ', GJ_ID, NULL,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        POSTING_STATUS
    FROM VECA.dbo.GJ_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VFIN: Receivable
    SELECT 'VFIN', 'VFIN_RECV', INVOICE_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.RECEIVABLES_RECEIVABLE_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Payable
    SELECT 'VFIN', 'VFIN_PAYB', INVOICE_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.PAYABLES_PAYABLE_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Payment
    SELECT 'VFIN', 'VFIN_PAYMENT', PAYMENT_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.CASHMGMT_PAYMENT_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: General Journal
    SELECT 'VFIN', 'VFIN_GEN', GEN_JOURNAL_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.LEDGER_GEN_JOURN_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Bank Adjustment
    SELECT 'VFIN', 'VFIN_BANKADJ', ADJUSTMENT_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.CASHMGMT_BANK_ADJ_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Direct Journal
    SELECT 'VFIN', 'VFIN_DIRECT', DIRECT_JOURNAL_ID, NULL,
        ISNULL(DEBIT_AMOUNT, 0), ISNULL(CREDIT_AMOUNT, 0),
        ISNULL(DEBIT_AMOUNT, 0) - ISNULL(CREDIT_AMOUNT, 0), 'P'
    FROM VFIN.dbo.LEDGER_DIRECT_JOURN_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
) AS Today
WHERE (@PostedOnly = 0 OR POSTING_STATUS = 'P')
GROUP BY SOURCE_DB, JOURNAL_TYPE
ORDER BY SOURCE_DB, SUM(DEBIT_AMOUNT) DESC;


/*
--------------------------------------------------------------------------------
  SECTION 2: Balance Check
  Debits should equal credits across each database. Non-zero = problem.
--------------------------------------------------------------------------------
*/
SELECT
    SOURCE_DB,
    ROUND(SUM(DEBIT_AMOUNT), 2)  AS TOTAL_DEBITS,
    ROUND(SUM(CREDIT_AMOUNT), 2) AS TOTAL_CREDITS,
    ROUND(SUM(NET_AMOUNT), 2)    AS OUT_OF_BALANCE
FROM (
    -- VECA dists
    SELECT 'VECA' AS SOURCE_DB,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END AS DEBIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END AS CREDIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END AS NET_AMOUNT,
        POSTING_STATUS
    FROM VECA.dbo.WIP_ISSUE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.WIP_RECEIPT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.SHIPMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.RECEIVABLE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.PURCHASE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.ADJUSTMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.INDIRECT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL SELECT 'VECA', CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END, POSTING_STATUS
    FROM VECA.dbo.GJ_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    -- VFIN dists
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.RECEIVABLES_RECEIVABLE_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.PAYABLES_PAYABLE_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.CASHMGMT_PAYMENT_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.LEDGER_GEN_JOURN_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.CASHMGMT_BANK_ADJ_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL SELECT 'VFIN', ISNULL(DEBIT_AMOUNT,0), ISNULL(CREDIT_AMOUNT,0),
        ISNULL(DEBIT_AMOUNT,0)-ISNULL(CREDIT_AMOUNT,0), 'P'
    FROM VFIN.dbo.LEDGER_DIRECT_JOURN_DIST
    WHERE POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR REFERENCE IS NULL OR REFERENCE NOT LIKE @ExchangeMark)
) AS BalCheck
WHERE (@PostedOnly = 0 OR POSTING_STATUS = 'P')
GROUP BY SOURCE_DB;


/*
--------------------------------------------------------------------------------
  SECTION 3: Detail by Account (with Z_GL_MAPPING)
  Full detail of every posting, enriched with account classification.
  Useful for drilling into specific accounts or finding unexpected postings.
--------------------------------------------------------------------------------
*/
SELECT
    D.SOURCE_DB,
    D.JOURNAL_TYPE,
    D.DOCUMENT_ID,
    D.WO_BASE_ID,
    D.LINKED_INVOICE_ID,
    D.GL_ACCOUNT_ID,
    G.DESCRIPTION                AS ACCT_DESCRIPTION,
    G.FS,
    G.FS_CAT,
    G.CATEGORY,
    ROUND(D.DEBIT_AMOUNT, 2)    AS DEBIT_AMOUNT,
    ROUND(D.CREDIT_AMOUNT, 2)   AS CREDIT_AMOUNT,
    ROUND(D.NET_AMOUNT, 2)      AS NET_AMOUNT,
    D.REFERENCE,
    D.SITE_OR_ENTITY
FROM (
    -- VECA: WIP Issue
    SELECT 'VECA' AS SOURCE_DB, 'VECA_WIP_ISSUE' AS JOURNAL_TYPE,
        NULL AS DOCUMENT_ID, WORKORDER_BASE_ID AS WO_BASE_ID, NULL AS LINKED_INVOICE_ID,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END AS DEBIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END AS CREDIT_AMOUNT,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END AS NET_AMOUNT,
        NULL AS REFERENCE, SITE_ID AS SITE_OR_ENTITY, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.WIP_ISSUE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: WIP Receipt
    SELECT 'VECA', 'VECA_WIP_RCPT', NULL, WORKORDER_BASE_ID, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.WIP_RECEIPT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Shipment
    SELECT 'VECA', 'VECA_SHIPMENT', CUST_ORDER_ID, NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.SHIPMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Receivable
    SELECT 'VECA', 'VECA_RECV', INVOICE_ID, NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.RECEIVABLE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Purchase
    SELECT 'VECA', 'VECA_PURCHASE', PURC_ORDER_ID, NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.PURCHASE_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Adjustment
    SELECT 'VECA', 'VECA_ADJUST', CAST(TRANSACTION_ID AS nvarchar(30)), NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.ADJUSTMENT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: Indirect
    SELECT 'VECA', 'VECA_INDIRECT', CAST(TRANSACTION_ID AS nvarchar(30)), NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.INDIRECT_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VECA: GJ
    SELECT 'VECA', 'VECA_GJ', GJ_ID, NULL, NULL,
        GL_ACCOUNT_ID, CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='CR' THEN AMOUNT ELSE 0 END,
        CASE WHEN AMOUNT_TYPE='DR' THEN AMOUNT ELSE -AMOUNT END,
        NULL, SITE_ID, POSTING_DATE, POSTING_STATUS
    FROM VECA.dbo.GJ_DIST
    WHERE POSTING_DATE = @AsOfDate AND @DedupeMode <> 'VFIN'
    UNION ALL
    -- VFIN: Receivable
    SELECT 'VFIN', 'VFIN_RECV', D.INVOICE_ID, NULL, NULL,
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, R.CUSTOMER_ID), D.INVOICE_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.RECEIVABLES_RECEIVABLE_DIST D
    JOIN VFIN.dbo.RECEIVABLES_RECEIVABLE R ON D.INVOICE_ENTITY_ID=R.ENTITY_ID AND D.INVOICE_ID=R.INVOICE_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Payable
    SELECT 'VFIN', 'VFIN_PAYB', D.INVOICE_ID, NULL, NULL,
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, P.SUPPLIER_ID), D.INVOICE_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.PAYABLES_PAYABLE_DIST D
    JOIN VFIN.dbo.PAYABLES_PAYABLE P ON D.INVOICE_ENTITY_ID=P.ENTITY_ID AND D.INVOICE_ID=P.INVOICE_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Payment
    SELECT 'VFIN', 'VFIN_PAYMENT', D.PAYMENT_ID, NULL,
        COALESCE(D.RECV_INVOICE_ID, D.PAYB_INVOICE_ID),
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, PM.REFERENCE), D.PAYMENT_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.CASHMGMT_PAYMENT_DIST D
    JOIN VFIN.dbo.CASHMGMT_PAYMENT PM ON D.PAYMENT_ENTITY_ID=PM.ENTITY_ID AND D.PAYMENT_ID=PM.PAYMENT_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: General Journal
    SELECT 'VFIN', 'VFIN_GEN', D.GEN_JOURNAL_ID, NULL, NULL,
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, G.DESCRIPTION), D.GEN_JOURNAL_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.LEDGER_GEN_JOURN_DIST D
    JOIN VFIN.dbo.LEDGER_GEN_JOURNAL G ON D.GEN_JOURNAL_ENTITY_ID=G.ENTITY_ID AND D.GEN_JOURNAL_ID=G.GEN_JOURNAL_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Bank Adjustment
    SELECT 'VFIN', 'VFIN_BANKADJ', D.ADJUSTMENT_ID, NULL, NULL,
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, A.REFERENCE), D.BANK_ADJ_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.CASHMGMT_BANK_ADJ_DIST D
    JOIN VFIN.dbo.CASHMGMT_BANK_ADJUSTMENT A ON D.BANK_ADJ_ENTITY_ID=A.ENTITY_ID AND D.ADJUSTMENT_ID=A.ADJUSTMENT_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
    UNION ALL
    -- VFIN: Direct Journal
    SELECT 'VFIN', 'VFIN_DIRECT', D.DIRECT_JOURNAL_ID, NULL, NULL,
        D.ACCOUNT_ID, ISNULL(D.DEBIT_AMOUNT,0), ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.DEBIT_AMOUNT,0)-ISNULL(D.CREDIT_AMOUNT,0),
        ISNULL(D.REFERENCE, J.DESCRIPTION), D.DIR_JOURN_ENTITY_ID, D.POSTING_DATE, 'P'
    FROM VFIN.dbo.LEDGER_DIRECT_JOURN_DIST D
    JOIN VFIN.dbo.LEDGER_DIRECT_JOURNAL J ON D.DIR_JOURN_ENTITY_ID=J.ENTITY_ID AND D.DIRECT_JOURNAL_ID=J.DIRECT_JOURNAL_ID
    WHERE D.POSTING_DATE = @AsOfDate
      AND @DedupeMode <> 'VECA'
      AND (@DedupeMode <> 'HYBRID' OR D.REFERENCE IS NULL OR D.REFERENCE NOT LIKE @ExchangeMark)
) AS D
LEFT JOIN VECA.dbo.Z_GL_MAPPING G
    ON D.GL_ACCOUNT_ID = G.ACCOUNT_ID
    AND D.POSTING_DATE >= G.EFFECTIVE_START_DATE
    AND D.POSTING_DATE < G.EFFECTIVE_END_DATE
WHERE (@PostedOnly = 0 OR D.POSTING_STATUS = 'P')
ORDER BY D.SOURCE_DB, D.JOURNAL_TYPE, D.GL_ACCOUNT_ID;
