use VTA
SELECT HOME_EMAIL AS EMAIL
FROM VTA.dbo.LABOR_EMPLOYEE
WHERE
CASE WHEN TERMINATION_DATE_2 IS NOT NULL THEN 'N' ELSE
CASE WHEN REHIRE_DATE IS NOT NULL THEN 'Y' ELSE
CASE WHEN TERMINATION_DATE IS NOT NULL THEN 'N' ELSE 'Y' END END END='Y'
AND STATUS='ACTIVE'
AND HOME_EMAIL IS NOT NULL
AND EMPLOYEE_TYPE<>'OTHER'
UNION
SELECT BUS_EMAIL
FROM VTA.dbo.LABOR_EMPLOYEE
WHERE
CASE WHEN TERMINATION_DATE_2 IS NOT NULL THEN 'N' ELSE
CASE WHEN REHIRE_DATE IS NOT NULL THEN 'Y' ELSE
CASE WHEN TERMINATION_DATE IS NOT NULL THEN 'N' ELSE 'Y' END END END='Y'
AND STATUS='ACTIVE'
AND BUS_EMAIL IS NOT NULL