

--This is the Open Orders for the next 45 Days
SELECT 

CUST_ORDER_LINE.PART_ID, 
sum(CUST_ORDER_LINE.ORDER_QTY - CUST_ORDER_LINE.TOTAL_SHIPPED_QTY) as Open_QTY


FROM 
VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE 
inner join 
VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER on CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID 

inner join  
VECA.dbo.CUSTOMER_ENTITY CUSTOMER_ENTITY on CUSTOMER_ENTITY.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID 

WHERE 
(CUSTOMER_ENTITY.CREDIT_STATUS='A') 
AND (CUST_ORDER_LINE.PART_ID Is Not Null) 
AND (CUSTOMER_ORDER.STATUS in ('R','F'))
AND (CUST_ORDER_LINE.LINE_STATUS='A') 
and CUSTOMER_ORDER.DESIRED_SHIP_DATE <= getdate()+45

group by 
CUST_ORDER_LINE.PART_ID

--This is the quantity available/on hand

SELECT 
PART_LOCATION.PART_ID, 
sum(PART_LOCATION.QTY) as Qty
FROM VECA.dbo.PART_LOCATION PART_LOCATION
WHERE (PART_LOCATION.LOCATION_ID In ('c2','c2-serialized'))
group by PART_LOCATION.PART_ID