SELECT 
CUSTOMER_ORDER.ORDER_DATE, 
CUSTOMER_ORDER.Desired_ship_date,
CUST_ORDER_LINE.PART_ID, 
CUST_ORDER_LINE.PRODUCT_CODE, 
CUST_ORDER_LINE.USER_ORDER_QTY,
CUST_ORDER_LINE.UNIT_PRICE * ((100-CUST_ORDER_LINE.TRADE_DISC_PERCENT)/100) * CUST_ORDER_LINE.USER_ORDER_QTY as Amount, 
'Sales Orders Entry' as Source,
CUST_ORDER_LINE.CUST_ORDER_ID,
CUST_ORDER_LINE.LINE_NO


FROM 

VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE inner join VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER
on CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID

where 
CUST_ORDER_LINE.LINE_STATUS = 'A' and CUSTOMER_ORDER.STATUS in ('R','F','C')

union all

SELECT 
CUSTOMER_ORDER.ORDER_DATE, 
CUSTOMER_ORDER.Desired_ship_date,
CUST_ORDER_LINE.PART_ID, 
CUST_ORDER_LINE.PRODUCT_CODE, 
CUST_ORDER_LINE.TOTAL_USR_SHIP_QTY,
CUST_ORDER_LINE.UNIT_PRICE * ((100-CUST_ORDER_LINE.TRADE_DISC_PERCENT)/100) * (CUST_ORDER_LINE.TOTAL_USR_SHIP_QTY) as Amount, 
'Closed Short Orders' as Source,
CUST_ORDER_LINE.CUST_ORDER_ID,
CUST_ORDER_LINE.LINE_NO

FROM 

VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE inner join VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER
on CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID

where 
CUST_ORDER_LINE.LINE_STATUS = 'C' and CUSTOMER_ORDER.STATUS in ('R','F','C')

union all

SELECT 
SHIPPER.SHIPPED_DATE, 
SHIPPER.SHIPPED_DATE as date2,
CUST_ORDER_LINE.PART_ID, 
CUST_ORDER_LINE.PRODUCT_CODE, 
-shipper_line.USER_SHIPPED_QTY as Qty, 
-shipper_line.USER_SHIPPED_QTY * ((100-shipper_line.TRADE_DISC_PERCENT)/100)* shipper_line.UNIT_PRICE as Amount, 
'Shipments' as Source,
CUST_ORDER_LINE.CUST_ORDER_ID, 
CUST_ORDER_LINE.LINE_NO

FROM 
VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE, VECA.dbo.SHIPPER SHIPPER, veca.dbo.Shipper_line shipper_line

WHERE shipper_line.PACKLIST_ID = SHIPPER.PACKLIST_ID AND CUST_ORDER_LINE.CUST_ORDER_ID = shipper_line.CUST_ORDER_ID AND CUST_ORDER_LINE.LINE_NO = shipper_line.CUST_ORDER_LINE_NO