USE VECA
SELECT CUSTOMER.ID, 'CUSTOMER' AS TYPE, STATUS_EFF_DATE AS DATESTAMP
FROM VECA.dbo.CUSTOMER
LEFT OUTER JOIN VFIN.dbo.RECEIVABLES_CUSTOMER
	ON CUSTOMER.ID=RECEIVABLES_CUSTOMER.ID
WHERE RECEIVABLES_CUSTOMER.ID IS NULL AND CUSTOMER.STATUS_EFF_DATE>='2022-01-01'

UNION

SELECT CUSTOMER_ORDER.ID, 'CUST_ORDER' AS TYPE, CUSTOMER_ORDER.CREATE_DATE AS DATESTAMP
FROM VECA.dbo.CUSTOMER_ORDER
LEFT OUTER JOIN VFIN.dbo.RECEIVABLES_CUSTOMER_ORDER
	ON CUSTOMER_ORDER.ID=RECEIVABLES_CUSTOMER_ORDER.CUST_ORDER_ID
WHERE RECEIVABLES_CUSTOMER_ORDER.CUST_ORDER_ID IS NULL AND CUSTOMER_ORDER.CREATE_DATE>='2022-01-01'

UNION

SELECT SHIPPER.PACKLIST_ID, 'SHIPPER' AS TYPE, SHIPPER.CREATE_DATE AS DATESTAMP
FROM VECA.dbo.SHIPPER
LEFT OUTER JOIN VFIN.dbo.RECEIVABLES_SHIPPER
	ON SHIPPER.PACKLIST_ID=RECEIVABLES_SHIPPER.SHIPPER_ID
WHERE RECEIVABLES_SHIPPER.SHIPPER_ID IS NULL AND SHIPPER.CREATE_DATE>='2022-01-01'

UNION

SELECT RECEIVABLE.INVOICE_ID, 'INVOICE' AS TYPE, RECEIVABLE.CREATE_DATE AS DATESTAMP
FROM VECA.dbo.RECEIVABLE
LEFT OUTER JOIN VFIN.dbo.RECEIVABLES_RECEIVABLE
	ON RECEIVABLE.INVOICE_ID=RECEIVABLES_RECEIVABLE.INVOICE_ID
WHERE RECEIVABLES_RECEIVABLE.INVOICE_ID IS NULL AND RECEIVABLE.CREATE_DATE>='2022-01-01'

UNION

SELECT VENDOR.ID, 'VENDOR' AS TYPE, VENDOR.STATUS_EFF_DATE AS DATESTAMP
FROM VECA.dbo.VENDOR
LEFT OUTER JOIN VFIN.dbo.PAYABLES_SUPPLIER
	ON VENDOR.ID=PAYABLES_SUPPLIER.ID
WHERE PAYABLES_SUPPLIER.ID IS NULL AND VENDOR.STATUS_EFF_DATE>='2022-01-01'

UNION

SELECT PURCHASE_ORDER.ID, 'PURC_ORDER' AS TYPE, PURCHASE_ORDER.CREATE_DATE AS DATESTAMP
FROM VECA.dbo.PURCHASE_ORDER
LEFT OUTER JOIN VFIN.dbo.PAYABLES_PURCHASE_ORDER
	ON PURCHASE_ORDER.ID=PAYABLES_PURCHASE_ORDER.PURC_ORDER_ID
WHERE PAYABLES_PURCHASE_ORDER.PURC_ORDER_ID IS NULL AND PURCHASE_ORDER.CREATE_DATE>='2022-01-01'

UNION

SELECT RECEIVER.ID, 'RECEIVER' AS TYPE, RECEIVER.CREATE_DATE AS DATESTAMP
FROM VECA.dbo.RECEIVER
LEFT OUTER JOIN VFIN.dbo.PAYABLES_RECEIVER
	ON RECEIVER.ID=PAYABLES_RECEIVER.RECEIVER_ID
WHERE PAYABLES_RECEIVER.RECEIVER_ID IS NULL AND RECEIVER.CREATE_DATE>='2022-01-01'

ORDER BY TYPE, DATESTAMP DESC, ID

