--Costing Utilities - Labor Ticket Check

use veca
SELECT LABOR_TICKET.EMPLOYEE_ID AS EMP_ID, LABOR_TICKET.RESOURCE_ID AS RSRC_ID, LABOR_TICKET.WORKORDER_BASE_ID AS BASE_ID, LABOR_TICKET.TRANSACTION_ID AS TRANS_ID, LABOR_TICKET.TRANSACTION_DATE AS TRANS_DATE, LABOR_TICKET.CLOCK_IN, LABOR_TICKET.CLOCK_OUT,
(CONVERT(DECIMAL(10,2), LABOR_TICKET.CLOCK_OUT)-CONVERT(DECIMAL(10, 2), LABOR_TICKET.CLOCK_IN))*24 AS HRS_WK,
LABOR_TICKET.HOURLY_COST AS HR_CST,
CONVERT(DECIMAL(10,2), LABOR_TICKET.CLOCK_IN) AS IN_DEC,
CONVERT(DECIMAL(10,2), LABOR_TICKET.CLOCK_OUT) AS OUT_DEC,
LABOR_TICKET.HOURLY_COST*(CONVERT(DECIMAL(10,4), LABOR_TICKET.CLOCK_OUT)-CONVERT(DECIMAL(10, 4), LABOR_TICKET.CLOCK_IN))*24 AS TCKT_CST,
LABOR_TICKET.HOURS_WORKED AS HRS_WRKD,
LABOR_TICKET.UNADJ_CLOCK_IN, LABOR_TICKET.UNADJ_CLOCK_OUT, LABOR_TICKET.DESCRIPTION AS 'DESC',
CHAR(39) + CONVERT(VARCHAR,TRANSACTION_ID) + CHAR(39)+CHAR(44)+' ' AS TRANS_STR,
OPERATION.STATUS AS STAT,
CONVERT(DECIMAL(10,1),OPERATION.CALC_START_QTY) AS QTY,
CONVERT(DECIMAL(10,2), LABOR_TICKET.HOURS_WORKED*LABOR_TICKET.HOURLY_COST/OPERATION.CALC_START_QTY) AS PC_CST

FROM LABOR_TICKET INNER JOIN OPERATION ON OPERATION.WORKORDER_BASE_ID=LABOR_TICKET.WORKORDER_BASE_ID
										AND OPERATION.WORKORDER_LOT_ID=LABOR_TICKET.WORKORDER_LOT_ID
										AND OPERATION.WORKORDER_SPLIT_ID=LABOR_TICKET.WORKORDER_SPLIT_ID
										AND OPERATION.WORKORDER_SUB_ID=LABOR_TICKET.WORKORDER_SUB_ID
										AND OPERATION.SEQUENCE_NO=LABOR_TICKET.OPERATION_SEQ_NO

WHERE MONTH(TRANSACTION_DATE)=MONTH(GETDATE()) AND YEAR(TRANSACTION_DATE)=YEAR(GETDATE())
AND LABOR_TICKET.DESCRIPTION IS NULL
AND (CONVERT(DECIMAL(10,4), LABOR_TICKET.CLOCK_OUT)-CONVERT(DECIMAL(10, 4), LABOR_TICKET.CLOCK_IN)>.5 OR
(CONVERT(DECIMAL(10,4), LABOR_TICKET.CLOCK_OUT)-CONVERT(DECIMAL(10, 4), LABOR_TICKET.CLOCK_IN))*LABOR_TICKET.HOURLY_COST>200)
ORDER BY LABOR_TICKET.EMPLOYEE_ID
;

/*
UPDATE LABOR_TICKET SET DESCRIPTION='LONG LABOR TICKET REVIEWED' WHERE TRANSACTION_ID IN (
'1111674', 
)

*/
 