use veca
SELECT
CUSTOMER_ORDER.ID, 
CUSTOMER_ORDER.CUSTOMER_ID, 
CUSTOMER.NAME, 
CUSTOMER.COUNTRY,
CUSTOMER.STATE, 
CUSTOMER_ENTITY.CREDIT_STATUS, 
CUSTOMER_ORDER.CUSTOMER_PO_REF, 
CUSTOMER_ORDER.ORDER_DATE, 
CUSTOMER_ORDER.DESIRED_SHIP_DATE, 
CUSTOMER_ORDER.STATUS, 
CUST_ORDER_LINE.PRODUCT_CODE AS 'SO PRODUCT CODE', 
CUST_ORDER_LINE.PART_ID, 
PART.DESCRIPTION, 
PART.QTY_AVAILABLE_MRP, 
PART.QTY_ON_ORDER,
CUST_ORDER_LINE.LINE_STATUS, 
(CUST_ORDER_LINE.ORDER_QTY - CUST_ORDER_LINE.TOTAL_SHIPPED_QTY) as 'BALANCE',
CUST_ORDER_LINE.TOTAL_AMT_ORDERED, 
PART.PRODUCT_CODE AS 'PART PRODUCT CODE', 
PART.COMMODITY_CODE,
CUST_ORDER_LINE.USER_5 AS PROD_WEEK,
CUST_ORDER_LINE.USER_6 AS SHIP_WEEK,
CUSTOMER_CARMS.CUSTOMER_NAME,
CUSTOMER_CARMS.CUSTOMER_GROUP,
CUSTOMER_CARMS.CUSTOMER_SUB_GROUP,
CUST_ORDER_LINE.USER_1 AS SERIAL_#,
CUST_ORDER_LINE.UNIT_PRICE*(100-CUST_ORDER_LINE.TRADE_DISC_PERCENT)/100 AS 'LINE PRICE',
b.HAS_WORKORDER_ATTACHED

FROM 
VECA.dbo.CUSTOMER_ORDER CUSTOMER_ORDER
INNER JOIN
VECA.dbo.CUST_ORDER_LINE CUST_ORDER_LINE
ON CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID
INNER JOIN
VECA.dbo.CUSTOMER CUSTOMER
ON CUSTOMER.ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN
VECA.dbo.CUSTOMER_ENTITY
ON CUSTOMER.ID = CUSTOMER_ENTITY.CUSTOMER_ID
INNER JOIN
VECA.dbo.PART PART
ON CUST_ORDER_LINE.PART_ID = PART.ID
INNER JOIN
VECA.dbo.CUSTOMER_CARMS
ON CUSTOMER.ID = CUSTOMER_CARMS.ID
LEFT OUTER JOIN
VECA.dbo.CUST_ADDRESS CUST_ADDRESS
ON CUSTOMER_ORDER.CUSTOMER_ID = CUST_ADDRESS.CUSTOMER_ID AND CUSTOMER_ORDER.SHIPTO_ID = CUST_ADDRESS.SHIPTO_ID
left outer JOIN
(select distinct case when workorder_base_id is null then 'TRUE' else 'FALSE' end as HAS_WORKORDER_ATTACHED, CUST_ORDER_ID from INVENTORY_TRANS where cust_order_id is not null group by WORKORDER_BASE_ID, CUST_ORDER_ID ) b
on CUSTOMER_ORDER.ID = b.CUST_ORDER_ID

WHERE CUSTOMER_ORDER.STATUS <> 'X' and CUSTOMER_ORDER.STATUS <> 'C' AND (PART.COMMODITY_CODE LIKE '%GUN%')



--select ID, part.description, part.order_policy, part_site.order_policy from veca.dbo.part inner join part_site on part.ID = part_site.part_ID where commodity_code like '%GUN%'
--select * from part