use lsa
SELECT COUNT(SHARED_CONFIG_KIOSK.MACHINE_ID) AS IN_USE
FROM LSA.dbo.LSA_LOGINS LEFT OUTER JOIN VTA.dbo.SHARED_CONFIG_KIOSK
ON SHARED_CONFIG_KIOSK.MACHINE_ID=LSA_LOGINS.PROGRAM_ID
WHERE LSA_LOGINS.LICENSE_NUMBER LIKE '%0C54%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%FB80%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%89D8%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%DF34%';

use lsa
SELECT SHARED_CONFIG_KIOSK.MACHINE_ID, LSA_LOGINS.PROGRAM_ID, LSA_LOGINS.LOGIN_TIME,
SHARED_CONFIG_KIOSK.DESCRIPTION, DATEADD(DD,0,DATEDIFF(DD,0,LSA_LOGINS.LOGIN_TIME)) AS LOGIN_DATE, LSA_LOGINS.LICENSE_NUMBER
FROM LSA.dbo.LSA_LOGINS LEFT OUTER JOIN VTA.dbo.SHARED_CONFIG_KIOSK
ON SHARED_CONFIG_KIOSK.MACHINE_ID=LSA_LOGINS.PROGRAM_ID
WHERE LSA_LOGINS.LICENSE_NUMBER LIKE '%0C54%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%FB80%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%89D8%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%DF34%'
order by LOGIN_TIME DESC, description, machine_id;
/*
DELETE FROM LSA_LOGINS WHERE LICENSE_NUMBER = '081D-0000-0003-4962-FD69-FB80' AND LOGIN_TIME<DATEADD(DD, -1, GETDATE())
DELETE FROM LSA_LOGINS WHERE PROGRAM_ID in ('PF-32P35G','DESKTOPMJ0EVXX5','MJ0GNK4T','MJ0FVV6F','MJ0FGP72','6Q5YBM2','B8H40F2','MJ0F1PYD','64DBSW1','20Y6LH1','896XD33','MJ0FGP6E','4Q5XHQ2','782B8V1','8GNQQ53')
DELETE FROM LSA_LOGINS
WHERE LICENSE_NUMBER LIKE '%89D8' or LICENSE_NUMBER LIKE '%FB80' or LICENSE_NUMBER LIKE '%DF34'
--PROGRAM_ID='3X4RR33' --AMY MOE
--PROGRAM_ID='HGY98M2' --LINDSEY FIELD
--PROGRAM_ID='57BRVV1' --DEBORAH KERR-FOX
--PROGRAM_ID='7CCSHQ2' --TYLER WHITLOCK
--PROGRAM_ID='B816HK2' --GREG BARTHOLOMEW
--AND 
--LOGIN_TIME<'2018-04-25' --SPECIFIC DATE
--LOGIN_TIME<DATEADD(DD,DATEDIFF(DD,0,GETDATE())-1,0) --MORE THAN A DAY OLD
;
*/
SELECT SHARED_CONFIG_KIOSK.MACHINE_ID, LSA_LOGINS.PROGRAM_ID, LSA_LOGINS.LOGIN_TIME,
SHARED_CONFIG_KIOSK.DESCRIPTION, DATEADD(DD,0,DATEDIFF(DD,0,LSA_LOGINS.LOGIN_TIME)) AS LOGIN_DATE, LSA_LOGINS.LICENSE_NUMBER
FROM LSA.dbo.LSA_LOGINS LEFT OUTER JOIN VTA.dbo.SHARED_CONFIG_KIOSK
ON SHARED_CONFIG_KIOSK.MACHINE_ID=LSA_LOGINS.PROGRAM_ID
WHERE LSA_LOGINS.LICENSE_NUMBER LIKE '%0C54%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%FB80%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%89D8%' OR LSA_LOGINS.LICENSE_NUMBER LIKE '%DF34%'
order by description, machine_id;

select * from LSA.dbo.LSA_LOGINS LEFT OUTER JOIN VTA.dbo.SHARED_CONFIG_KIOSK on SHARED_CONFIG_KIOSK.MACHINE_ID = LSA_LOGINS.PROGRAM_ID

