SELECT WORKORDER_BASE_ID, REQUIREMENT.PART_ID FROM REQUIREMENT 
INNER JOIN PART_SITE ON REQUIREMENT.WORKORDER_BASE_ID = dbo.PART_SITE.PART_ID 
AND REQUIREMENT.WORKORDER_LOT_ID = PART_SITE.ENGINEERING_MSTR where Requirement.part_id is not null