SELECT ID,DOCUMENT_ID, PACKLIST_ID, ORDER_ID,USER_DEF_FIELDS.LINE_NO,STRING_VAL,TRACKING_NUMBER,VOID,DATE_EXPORTED,DEST_NAME,ADDR1,POSTAL_CODE
FROM USER_DEF_FIELDS
INNER JOIN Z_UPS_SHIPMENTS
ON USER_DEF_FIELDS.DOCUMENT_ID = Z_UPS_SHIPMENTS.PACKLIST_ID
where STRING_VAL!= TRACKING_NUMBER AND STRING_VAL IS NOT NULL and LEN(STRING_VAL) < 15 
ORDER BY PACKLIST_ID