use veca
SELECT 
				INVENTORY_TRANS.TRANSACTION_ID, 

				INVENTORY_TRANS.WORKORDER_BASE_ID, 
				
				PART.ID as SKU,
				
				PART.DESCRIPTION,

                CONVERT(NVARCHAR(MAX),CONVERT(VARBINARY(MAX),PART_CO_BINARY.BITS)) AS LONG_DESC,

                USER_DEF_FIELDS.STRING_VAL AS PRODUCT,

				TRACE_INV_TRANS.TRACE_ID,

				PART.USER_6 AS UPC
				
FROM INVENTORY_TRANS INNER JOIN TRACE_INV_TRANS

ON INVENTORY_TRANS.TRANSACTION_ID = TRACE_INV_TRANS.TRANSACTION_ID AND INVENTORY_TRANS.PART_ID = TRACE_INV_TRANS.PART_ID

inner join part on part.id = trace_inv_trans.part_id

LEFT OUTER JOIN PART_CO_BINARY ON PART_CO_BINARY.PART_ID=PART.ID

LEFT OUTER JOIN USER_DEF_FIELDS ON USER_DEF_FIELDS.DOCUMENT_ID=PART.ID AND USER_DEF_FIELDS.ID='UDF-0000021'

WHERE INVENTORY_TRANS.WORKORDER_BASE_ID IS NOT NULL AND INVENTORY_TRANS.CUST_ORDER_ID IS NULL and
INVENTORY_TRANS.WORKORDER_BASE_ID = '463091' and

(part.commodity_code like 'act%' or part.commodity_code like '%gun%' or part.commodity_code like '%ass%')
order by inventory_trans.transaction_id desc