SELECT r.PART_ID, SUM(r.CALC_QTY - r.ISSUED_QTY) AS on_wo_not_issued 
FROM dbo.WORK_ORDER AS wo 
INNER JOIN dbo.REQUIREMENT AS r ON wo.BASE_ID = r.WORKORDER_BASE_ID 
WHERE wo.CREATE_DATE > GETDATE() - 30 AND wo.TYPE = 'W' AND wo.STATUS = 'R' 
AND r.PART_ID IS NOT NULL 
GROUP BY r.PART_ID