SELECT
    t.TEXT QueryName,
    t.*,
    last_elapsed_time
FROM
    sys.dm_exec_query_stats s
    CROSS APPLY sys.dm_exec_sql_text(s.sql_handle) t
order by
    last_elapsed_time DESC
    /*================================================  -- Author:  Greg Van Riper  -- Create date: 04/21/2016  -- Description: Get invoices to send.  ================================================  ==CHANGE LOG:===================================  02/28/2017 - Greg Van Riper  - Added custom procedure ability.    05/25/2017 - Greg Van Riper  - Added backorder ability.    07/27/2017 - Greg Van Riper  - Added OBJECT_NAME(@@PROCID) to prevent custom SP issues.    09/08/2017 - Greg Van Riper  - Programmed dynamic SQL.    10/06/2017 - Greg Van Riper  - Added Global Financials queries.    11/13/2017 - Greg Van Riper  - Fixed query to use EDI_SL_DASH_HEADER_INVOICE table.    05/24/2018 - Greg Van Riper  - Handle new [ESI_SL] schema.    06/06/2018 - Greg Van Riper  - Convert to DATE when comparing dates.    07/27/2018 - Greg Van Riper  - Added [SITE_ID] and [PLANT_ID].    12/10/2018 - Greg Van Riper  - Changed CUSTOMER table to ESI_CUSTOMER.    02/21/2019 - Greg Van Riper  - Fixed the query to require the inbound PO was approved.    03/21/2019 - Greg Van Riper  - Added [ERP_CUSTOMER_ID] and [SITE_ID] to filter views.    06/05/2019 - Greg Van Riper  - Fixed locking hints. I found that the NOLOCK caused, if reapproved, to generate another duplicate record.    07/25/2019 - Greg Van Riper  - Fixed redundant joins.    09/19/2019 - Daniel Montemayor - Re-written for Core.    04/28/2020 - Michael D Wagner - filter out customer order 0s.    05/01/2020 - Greg Van Riper  - Made CUSTOMER_ORDER_ID '0' instead of an INT. All other ERPs are VARCHAR.  ================================================  */
    CREATE PROCEDURE [ESI_EDI].[sp_ESI_Get_Invoices_To_Send] (@SQL_PROFILE VARCHAR(50)) AS BEGIN --Declare variables.--   
    DECLARE @CUSTOM_PROCEDURE VARCHAR(150),
    @ERP_SOFTWARE VARCHAR(40),
    @SQL_QUERY NVARCHAR(MAX),
    @GLOBAL_FINANCIALS_ENABLED VARCHAR(50),
    @GLOBAL_FINANCIALS_DB VARCHAR(MAX),
    @p_SQL_PROFILE VARCHAR(50) = @SQL_PROFILE --Table to return--   
    DECLARE @tbl_RECEIVABLE TABLE (
        [INVOICE_ID] VARCHAR(50),
        [SITE_ID] VARCHAR(50),
        [PLANT_ID] VARCHAR(50),
        [WAREHOUSE_ID] VARCHAR(50)
    )
SELECT
    TOP 1 @ERP_SOFTWARE = [ERP_SOFTWARE]
FROM
    [ESI_CORE].[ESI_GLOBAL] WITH (NOLOCK)
WHERE
    [DELETE_DATE] IS NULL --Try getting the custom procedure.--   
SELECT
    @CUSTOM_PROCEDURE = [ESI_CORE].[udf_ESI_Get_Custom_Stored_Procedure](NULL, OBJECT_NAME(@ @PROCID)) IF (ISNULL(@CUSTOM_PROCEDURE, '') <> '') BEGIN EXEC @CUSTOM_PROCEDURE @SQL_PROFILE = @p_SQL_PROFILE
END
ELSE BEGIN --Check if Global Financials is used.--     
SELECT
    @GLOBAL_FINANCIALS_ENABLED = [ESI_CORE].[udf_ESI_Get_Setting_Value]('GLOBAL_FINANCIALS_ENABLED', NULL) IF (@p_SQL_PROFILE = 'ERPTestSQLSetting') --Test SQL Profile.      
    BEGIN --Non-EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_TEST] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.[SEND_NON_EDI] = '1'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_TEST] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = ERP_INH.[CUSTOMER_ORDER_ID]
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --Get using possible original order. This is for backorders.--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_TEST] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = SUBSTRING(
        CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]),
        0,
        CASE
            WHEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            ) > 0 THEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            )
            ELSE LEN(ERP_INH.[CUSTOMER_ORDER_ID]) + 1
        END
    )
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1'
SELECT
    DISTINCT [INVOICE_ID],
    [SITE_ID],
    [PLANT_ID],
    [WAREHOUSE_ID]
FROM
    @tbl_RECEIVABLE
END
ELSE IF (@p_SQL_PROFILE = 'ERPPlaySQLSetting') --Play SQL Profile.      
BEGIN --Non-EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_PLAY] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.[SEND_NON_EDI] = '1'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_PLAY] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = ERP_INH.[CUSTOMER_ORDER_ID]
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --Get using possible original order. This is for backorders.--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER_PLAY] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = SUBSTRING(
        CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]),
        0,
        CASE
            WHEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            ) > 0 THEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            )
            ELSE LEN(ERP_INH.[CUSTOMER_ORDER_ID]) + 1
        END
    )
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1'
SELECT
    DISTINCT [INVOICE_ID],
    [SITE_ID],
    [PLANT_ID],
    [WAREHOUSE_ID]
FROM
    @tbl_RECEIVABLE
END
ELSE --Production SQL Profile.      
BEGIN --Non-EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.[SEND_NON_EDI] = '1'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --EDI Invoices--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = ERP_INH.[CUSTOMER_ORDER_ID]
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1' --Get using possible original order. This is for backorders.--       
INSERT INTO
    @tbl_RECEIVABLE (
        [INVOICE_ID],
        [SITE_ID],
        [PLANT_ID],
        [WAREHOUSE_ID]
    )
SELECT
    DISTINCT ERP_INH.[INVOICE_ID],
    ERP_INH.[SITE_ID],
    ERP_INH.[PLANT_ID],
    ERP_INH.[WAREHOUSE_ID]
FROM
    [ESI_CORE].[v_ERP_INVOICE_HEADER] ERP_INH WITH (NOLOCK)
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER_INVOICE] EDI_INH WITH (READCOMMITTED) ON EDI_INH.[INVOICE_ID] = ERP_INH.[INVOICE_ID]
    LEFT JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH WITH (READCOMMITTED) ON EDI_ORH.[ESI_DASH_HEADER_ID] = EDI_INH.[ESI_DASH_HEADER_ID]
    AND EDI_ORH.[DOCUMENT_TYPE] = '810'
    AND EDI_ORH.[EDI_DIRECTION] = 'O'
    AND ISNULL(EDI_ORH.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER] EDI_CST WITH (NOLOCK) ON EDI_CST.[ERP_CUSTOMER_ID] = ERP_INH.[ERP_CUSTOMER_ID]
    AND ISNULL(EDI_CST.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    INNER JOIN [ESI_CORE].[ESI_CUSTOMER_DOCUMENT_TYPE] EDI_DCT WITH (NOLOCK) ON EDI_DCT.[ESI_CUSTOMER_ID] = EDI_CST.[ESI_CUSTOMER_ID]
    INNER JOIN [ESI_CORE].[ESI_DOCUMENT_TYPE] EDI_DOT WITH (NOLOCK) ON EDI_DOT.[DOCUMENT_TYPE] = EDI_DCT.[DOCUMENT_TYPE]
    AND EDI_DOT.[EDI_DIRECTION] = EDI_DCT.[EDI_DIRECTION]
    INNER JOIN [ESI_EDI].[ESI_DASH_HEADER] EDI_ORH_I WITH (NOLOCK) ON EDI_ORH_I.[CUSTOMER_ORDER_ID] = SUBSTRING(
        CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]),
        0,
        CASE
            WHEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            ) > 0 THEN CHARINDEX(
                '-',
                (CONVERT(VARCHAR(20), ERP_INH.[CUSTOMER_ORDER_ID]))
            )
            ELSE LEN(ERP_INH.[CUSTOMER_ORDER_ID]) + 1
        END
    )
    AND ISNULL(EDI_ORH_I.[SITE_ID], '') = ISNULL(ERP_INH.[SITE_ID], '')
    AND EDI_ORH_I.[DOCUMENT_TYPE] IN ('830', '850', '860', '862')
    AND EDI_ORH_I.[EDI_DIRECTION] = 'I'
    AND EDI_ORH_I.[EDI_STATUS] = 'A'
    AND EDI_ORH_I.[CUSTOMER_ORDER_ID] <> '0'
WHERE
    ERP_INH.[TYPE] = 'I'
    AND CONVERT(DATE, ERP_INH.[INVOICE_DATE]) >= CONVERT(DATE, EDI_DCT.[ACTIVE_DATE])
    AND EDI_INH.[INVOICE_ID] IS NULL
    AND EDI_DCT.SEND_NON_EDI = '0'
    AND EDI_DCT.[DOCUMENT_TYPE] = '810'
    AND EDI_DCT.[EDI_DIRECTION] = 'O'
    AND EDI_DCT.[DELETE_DATE] IS NULL
    AND EDI_CST.[DELETE_DATE] IS NULL
    AND EDI_DOT.[IS_ENABLED] = '1'
SELECT
    DISTINCT [INVOICE_ID],
    [SITE_ID],
    [PLANT_ID],
    [WAREHOUSE_ID]
FROM
    @tbl_RECEIVABLE
END
END
END