-- Costing Utilities - Bad Inventory Adjustments

USE VECA
SELECT I.CLASS AS C, I.TYPE AS T, I.TRANSACTION_ID AS T_ID, I.TRANSACTION_DATE AS T_DATE, I.USER_ID, I.PART_ID, P.DESCRIPTION, I.QTY, I.DESCRIPTION, CONVERT(DECIMAL(10,2),I.ACT_MATERIAL_COST) AS MATL, CONVERT(DECIMAL(10,2),I.ACT_LABOR_COST) AS LBR, CONVERT(DECIMAL(10,2),I.ACT_SERVICE_COST) AS SVC, CONVERT(DECIMAL(10,2),I.ACT_BURDEN_COST) AS BURD, CONVERT(DECIMAL(10,2),I.ACT_MATERIAL_COST/I.QTY) AS PC, P.STOCK_UM AS UOM, I.DESCRIPTION AS TRANS_DESC,CHAR(39) + CONVERT(VARCHAR,I.TRANSACTION_ID) + CHAR(39)+CHAR(44)+' ' AS TRANS_STR
FROM INVENTORY_TRANS I INNER JOIN PART P ON I.PART_ID=P.ID
WHERE I.CLASS='A' AND YEAR(I.CREATE_DATE)=YEAR(GETDATE()) AND MONTH(I.CREATE_DATE)>MONTH(GETDATE()-180) AND I.DESCRIPTION NOT LIKE '%TRANSFER%' and I.DESCRIPTION NOT LIKE '%REVIEWED%'
AND (I.ACT_MATERIAL_COST>10000 OR I.ACT_MATERIAL_COST/I.QTY>250)
ORDER BY I.USER_ID, I.TRANSACTION_ID;

/*
UPDATE INVENTORY_TRANS SET DESCRIPTION=DESCRIPTION+'-TRANSACTION REVIEWED' WHERE TRANSACTION_ID IN (
'4682088'
);

