USE master
--Change database name to the restore file you will be using.
ALTER DATABASE VECA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE VECA FROM DISK = '\\stor\bak\Backups\SQL\CARMS\VECA_backup_2022_06_22_232217_5556240.bak' 
GO
ALTER DATABASE VECA SET MULTI_USER
GO

ALTER DATABASE VTA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE VTA FROM DISK = '\\stor\bak\Backups\SQL\CARMS\VTA_backup_2022_06_22_232217_7472148.bak' 
GO
ALTER DATABASE VTA SET MULTI_USER
GO

ALTER DATABASE VFIN SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE VFIN FROM DISK = '\\stor\bak\Backups\SQL\CARMS\VFIN_backup_2022_06_22_232217_6690808.bak' 
GO
ALTER DATABASE VFIN SET MULTI_USER
GO