USE VECA
SELECT USER_ID, COUNT(USER_ID) AS PGRM_CNT, MIN(LAST_ACTIVITY) AS LAST_ACT, 'DELETE FROM DBO.LOGINS WHERE USER_ID='''+USER_ID+''';' FROM DBO.LOGINS GROUP BY USER_ID,'DELETE FROM DBO.LOGINS WHERE USER_ID='+USER_ID+';' HAVING COUNT(USER_ID)<2 AND MIN(LAST_ACTIVITY)<DATEADD(MINUTE, -5, GETDATE());
SELECT COUNT(DISTINCT MACHINE_ID) FROM DBO.LOGINS;
SELECT PROGRAM_ID, LOGIN_TIME, LAST_ACTIVITY, USER_ID FROM DBO.LOGINS ORDER BY USER_ID, LAST_ACTIVITY DESC;
SELECT PROGRAM_ID, LOGIN_TIME, LAST_ACTIVITY, USER_ID FROM DBO.LOGINS ORDER BY PROGRAM_ID;
SELECT DISTINCT USER_ID, MACHINE_ID 
	CASE WHEN MACHINE_ID='776B6774837575776A66787E6D6B6873' THEN '3CAEX' ELSE 'SOMEONE ELSE' END END AS 'UID' FROM DBO.LOGINS ORDER BY USER_ID;
SELECT DISTINCT MACHINE_ID FROM DBO.LOGINS;
SELECT * FROM DBO.LOGINS WHERE USER_ID='SYSADM';
SELECT DISTINCT S.USER_ID, S.MACHINE_ID, A.USER_ID, A.MACHINE_ID 
	FROM DBO.LOGINS S INNER JOIN DBO.LOGINS A 
	ON A.MACHINE_ID=S.MACHINE_ID
	WHERE S.USER_ID<>A.USER_ID AND A.USER_ID='SYSADM';

/*
DELETE FROM DBO.LOGINS WHERE USER_ID IN ('BRABLA','BRABUR');		DELETE FROM DBO.LOGINS WHERE USER_ID NOT IN ('AMMONS','SYSADM','BRENTW','TYLWHI','SCOTTC');
DELETE FROM DBO.LOGINS WHERE USER_ID NOT IN ('AMMONS','SYSADM','SCOTTC');										DELETE FROM DBO.LOGINS WHERE USER_ID='AMMONS' AND LOGIN_TIME<'2019-12-21 01:23:51.200'
DELETE FROM DBO.LOGINS WHERE LOGIN_TIME<'2019-12-21 01:23:51.200'												DELETE FROM DBO.LOGINS WHERE USER_ID NOT IN ('SHIRAN');
DELETE FROM DBO.LOGINS WHERE USER_ID NOT IN ('SYSADM');															DELETE FROM DBO.LOGINS
DELETE FROM DBO.LOGINS WHERE USER_ID='MICNEI';
*/
-- SCOTT'S MACHINE 776B676B6E67768A88786A6D6B758685
/*
SELECT PROGRAM_ID, LOGIN_TIME, LAST_ACTIVITY, USER_ID, MACHINE_ID FROM DBO.LOGINS where USER_ID = 'HUNWHI' ORDER BY PROGRAM_ID;
DELETE FROM DBO.LOGINS WHERE MACHINE_ID IN ('776B676A797565686A74786C797A6B79');
*/

--SELECT USER_ID, MACHINE_ID from (SELECT DISTINCT USER_ID, MACHINE_ID, CASE WHEN MACHINE_ID='776B6774837575776A66787E6D6B6873' THEN '3CAEX' ELSE 'SOMEONE ELSE' END AS 'UID' FROM DBO.LOGINS) t1 where 
	

--(select USER_ID from customers group by emailaddress having count(*) > 1)
/*
DELETE FROM DBO.LOGINS WHERE USER_ID='JEFBRA';
*/
