-- This query creates a current trial balance
--*** Please update the dates

--Query 1 creates a balanced TB
SELECT 
gl.account_id,
gl.description,
--Substitutes for unbalanced GL.
case gl.account_id when '2195' then gl.balance + 8 else gl.balance end as Balance


from(
SELECT 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION, 

sum(LEDGER_ACCOUNT_BALANCE.DEBIT_AMOUNT-LEDGER_ACCOUNT_BALANCE.CREDIT_AMOUNT) as Balance

FROM VFIN.dbo.LEDGER_ACCOUNT LEDGER_ACCOUNT inner join VFIN.dbo.LEDGER_ACCOUNT_BALANCE LEDGER_ACCOUNT_BALANCE
on LEDGER_ACCOUNT.ACCOUNT_ID = LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID 

--update dates to desired TB dates
WHERE ((LEDGER_ACCOUNT.POSTING_LEVEL=1) AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE<={ts '2021-08-31 00:00:00'}) and left(ledger_account.account_ID,1)<4) 

group by 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION

union all

SELECT 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION, 

sum(LEDGER_ACCOUNT_BALANCE.DEBIT_AMOUNT-LEDGER_ACCOUNT_BALANCE.CREDIT_AMOUNT) as Balance

FROM VFIN.dbo.LEDGER_ACCOUNT LEDGER_ACCOUNT inner join VFIN.dbo.LEDGER_ACCOUNT_BALANCE LEDGER_ACCOUNT_BALANCE
on LEDGER_ACCOUNT.ACCOUNT_ID = LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID 

--Update to current TB dates
WHERE ((LEDGER_ACCOUNT.POSTING_LEVEL=1) AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE<={ts '2021-08-31 00:00:00'})AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE>={ts '2021-01-01 00:00:00'})and left(ledger_account.account_ID,1)>3) 

group by 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION) as GL




SELECT 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION, 

sum(LEDGER_ACCOUNT_BALANCE.DEBIT_AMOUNT-LEDGER_ACCOUNT_BALANCE.CREDIT_AMOUNT) as Balance

FROM VFIN.dbo.LEDGER_ACCOUNT LEDGER_ACCOUNT inner join VFIN.dbo.LEDGER_ACCOUNT_BALANCE LEDGER_ACCOUNT_BALANCE
on LEDGER_ACCOUNT.ACCOUNT_ID = LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID 

WHERE ((LEDGER_ACCOUNT.POSTING_LEVEL=1) AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE<={ts '2021-09-30 00:00:00'}) and left(ledger_account.account_ID,1)<4) 

group by 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION

union all

SELECT 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION, 

sum(LEDGER_ACCOUNT_BALANCE.DEBIT_AMOUNT-LEDGER_ACCOUNT_BALANCE.CREDIT_AMOUNT) as Balance

FROM VFIN.dbo.LEDGER_ACCOUNT LEDGER_ACCOUNT inner join VFIN.dbo.LEDGER_ACCOUNT_BALANCE LEDGER_ACCOUNT_BALANCE
on LEDGER_ACCOUNT.ACCOUNT_ID = LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID 

WHERE ((LEDGER_ACCOUNT.POSTING_LEVEL=1) AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE<={ts '2021-09-30 00:00:00'})AND (LEDGER_ACCOUNT_BALANCE.POSTING_DATE>={ts '2021-01-01 00:00:00'})and left(ledger_account.account_ID,1)>3) 

group by 
LEDGER_ACCOUNT_BALANCE.ACCOUNT_ID, 
LEDGER_ACCOUNT.DESCRIPTION